blank_issues_enabled: false
contact_links:
  - name: SparkyFitness Support
    url: https://github.com/CodeWithCJ/SparkyFitness/discussions
    about: Please ask and answer questions here.
  - name: SparkyFitness Discord
    url: https://discord.gg/vcnMT5cPEA
    about: Chat with the community and get fast help on Discord.

