apiVersion: v1
kind: Service
metadata:
  name: {{ include "sparkyfitness.fullname" . }}-frontend
  labels:
    {{- include "sparkyfitness.labels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
  {{- if .Values.frontend.service.annotations }}
  annotations:
    {{- toYaml .Values.frontend.service.annotations | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.frontend.service.type | default "ClusterIP" }}
  ports:
    - port: {{ .Values.frontend.service.port | default .Values.frontend.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "sparkyfitness.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
