{{- include "sparkyfitness.validateRouting" . }}
{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "sparkyfitness.fullname" . }}
  labels:
    {{- include "sparkyfitness.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- with .Values.ingress.className }}
  ingressClassName: {{ . }}
  {{- end }}
  {{- if .Values.ingress.tls }}
  tls:
    {{- toYaml .Values.ingress.tls | nindent 4 }}
  {{- end }}
  rules:
    {{- $serverPaths := .Values.ingress.serverPaths | default list }}
    {{- range .Values.ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
          {{- range $serverPaths }}
          - path: {{ . }}
            pathType: Prefix
            backend:
              service:
                name: {{ include "sparkyfitness.fullname" $ }}-server
                port:
                  name: http
          {{- end }}
          {{- range .paths }}
          - path: {{ .path }}
            pathType: {{ .pathType }}
            backend:
              service:
                name: {{ include "sparkyfitness.fullname" $ }}-frontend
                port:
                  name: http
          {{- end }}
    {{- end }}
{{- end }}
