{{- if and .Values.externalSecrets.enabled .Values.externalSecrets.smtp.enabled }}
apiVersion: external-secrets.io/{{ .Values.externalSecrets.apiVersion }}
kind: ExternalSecret
metadata:
  name: {{ include "sparkyfitness.fullname" . }}-smtp
  labels:
    {{- include "sparkyfitness.labels" . | nindent 4 }}
spec:
  refreshInterval: {{ .Values.externalSecrets.refreshInterval | default "1h" | quote }}
  secretStoreRef:
    name: {{ .Values.externalSecrets.secretStore.name }}
    kind: SecretStore
  target:
    name: {{ include "sparkyfitness.smtpSecretName" . }}
    creationPolicy: Owner
  data:
    {{- range .Values.externalSecrets.smtp.keys }}
    - secretKey: {{ .secretKey }}
      remoteRef:
        key: {{ $.Values.externalSecrets.smtp.remoteKey }}
        property: {{ .property }}
    {{- end }}
{{- end }}
