// Generated by ts-to-zod
import { z } from "zod";

export const accountIdSchema = z.string().and(
  z.object({
    __brand: z.literal("public.account"),
  }),
);

const userIdSchema = z.any();

export const accountSchema = z.object({
  id: accountIdSchema,
  account_id: z.string(),
  provider_id: z.string(),
  user_id: userIdSchema,
  access_token: z.string().nullable(),
  refresh_token: z.string().nullable(),
  id_token: z.string().nullable(),
  access_token_expires_at: z.date().nullable(),
  refresh_token_expires_at: z.date().nullable(),
  scope: z.string().nullable(),
  password: z.string().nullable(),
  created_at: z.date(),
  updated_at: z.date(),
});

export const accountInitializerSchema = z.object({
  id: accountIdSchema.optional(),
  account_id: z.string(),
  provider_id: z.string(),
  user_id: userIdSchema,
  access_token: z.string().optional().nullable(),
  refresh_token: z.string().optional().nullable(),
  id_token: z.string().optional().nullable(),
  access_token_expires_at: z.date().optional().nullable(),
  refresh_token_expires_at: z.date().optional().nullable(),
  scope: z.string().optional().nullable(),
  password: z.string().optional().nullable(),
  created_at: z.date().optional(),
  updated_at: z.date().optional(),
});

export const accountMutatorSchema = z.object({
  id: accountIdSchema.optional(),
  account_id: z.string().optional(),
  provider_id: z.string().optional(),
  user_id: userIdSchema.optional(),
  access_token: z.string().optional().nullable(),
  refresh_token: z.string().optional().nullable(),
  id_token: z.string().optional().nullable(),
  access_token_expires_at: z.date().optional().nullable(),
  refresh_token_expires_at: z.date().optional().nullable(),
  scope: z.string().optional().nullable(),
  password: z.string().optional().nullable(),
  created_at: z.date().optional(),
  updated_at: z.date().optional(),
});

export type Account = z.infer<typeof accountSchema>;
export type AccountInitializer = z.infer<typeof accountInitializerSchema>;
export type AccountMutator = z.infer<typeof accountMutatorSchema>;
