// Generated by ts-to-zod
import { z } from "zod";

export const adminActivityLogsIdSchema = z.string().and(
  z.object({
    __brand: z.literal("public.admin_activity_logs"),
  }),
);

const userIdSchema = z.any();

export const adminActivityLogsSchema = z.object({
  id: adminActivityLogsIdSchema,
  admin_user_id: userIdSchema.nullable(),
  target_user_id: userIdSchema.nullable(),
  action_type: z.string(),
  details: z.unknown().nullable(),
  created_at: z.date().nullable(),
});

export const adminActivityLogsInitializerSchema = z.object({
  id: adminActivityLogsIdSchema.optional(),
  admin_user_id: userIdSchema.optional().nullable(),
  target_user_id: userIdSchema.optional().nullable(),
  action_type: z.string(),
  details: z.unknown().optional().nullable(),
  created_at: z.date().optional().nullable(),
});

export const adminActivityLogsMutatorSchema = z.object({
  id: adminActivityLogsIdSchema.optional(),
  admin_user_id: userIdSchema.optional().nullable(),
  target_user_id: userIdSchema.optional().nullable(),
  action_type: z.string().optional(),
  details: z.unknown().optional().nullable(),
  created_at: z.date().optional().nullable(),
});

export type AdminActivityLogs = z.infer<typeof adminActivityLogsSchema>;
export type AdminActivityLogsInitializer = z.infer<
  typeof adminActivityLogsInitializerSchema
>;
export type AdminActivityLogsMutator = z.infer<
  typeof adminActivityLogsMutatorSchema
>;
