// Generated by ts-to-zod
import { z } from "zod";

export const apiKeyIdSchema = z.string().and(
  z.object({
    __brand: z.literal("public.api_key"),
  }),
);

const userIdSchema = z.any();

export const apiKeySchema = z.object({
  id: apiKeyIdSchema,
  name: z.string().nullable(),
  key: z.string(),
  user_id: userIdSchema.optional(),
  metadata: z.string().nullable(),
  created_at: z.date().nullable(),
  updated_at: z.date().nullable(),
  expires_at: z.date().nullable(),
  last_used_at: z.date().nullable(),
  start: z.string().nullable(),
  prefix: z.string().nullable(),
  refill_interval: z.number().nullable(),
  refill_amount: z.number().nullable(),
  last_refill_at: z.date().nullable(),
  enabled: z.boolean().nullable(),
  rate_limit_enabled: z.boolean().nullable(),
  rate_limit_time_window: z.number().nullable(),
  rate_limit_max: z.number().nullable(),
  request_count: z.number().nullable(),
  remaining: z.number().nullable(),
  last_request: z.date().nullable(),
  permissions: z.string().nullable(),
  reference_id: z.string().nullable().optional(),
  config_id: z.string().nullable().optional(),
});

export const apiKeyInitializerSchema = z.object({
  id: apiKeyIdSchema,
  name: z.string().optional().nullable(),
  key: z.string(),
  user_id: userIdSchema.optional(),
  metadata: z.string().optional().nullable(),
  created_at: z.date().optional().nullable(),
  updated_at: z.date().optional().nullable(),
  expires_at: z.date().optional().nullable(),
  last_used_at: z.date().optional().nullable(),
  start: z.string().optional().nullable(),
  prefix: z.string().optional().nullable(),
  refill_interval: z.number().optional().nullable(),
  refill_amount: z.number().optional().nullable(),
  last_refill_at: z.date().optional().nullable(),
  enabled: z.boolean().optional().nullable(),
  rate_limit_enabled: z.boolean().optional().nullable(),
  rate_limit_time_window: z.number().optional().nullable(),
  rate_limit_max: z.number().optional().nullable(),
  request_count: z.number().optional().nullable(),
  remaining: z.number().optional().nullable(),
  last_request: z.date().optional().nullable(),
  permissions: z.string().optional().nullable(),
  reference_id: z.string().optional().nullable(),
  config_id: z.string().optional().nullable(),
});

export const apiKeyMutatorSchema = z.object({
  id: apiKeyIdSchema.optional(),
  name: z.string().optional().nullable(),
  key: z.string().optional(),
  user_id: userIdSchema.optional(),
  metadata: z.string().optional().nullable(),
  created_at: z.date().optional().nullable(),
  updated_at: z.date().optional().nullable(),
  expires_at: z.date().optional().nullable(),
  last_used_at: z.date().optional().nullable(),
  start: z.string().optional().nullable(),
  prefix: z.string().optional().nullable(),
  refill_interval: z.number().optional().nullable(),
  refill_amount: z.number().optional().nullable(),
  last_refill_at: z.date().optional().nullable(),
  enabled: z.boolean().optional().nullable(),
  rate_limit_enabled: z.boolean().optional().nullable(),
  rate_limit_time_window: z.number().optional().nullable(),
  rate_limit_max: z.number().optional().nullable(),
  request_count: z.number().optional().nullable(),
  remaining: z.number().optional().nullable(),
  last_request: z.date().optional().nullable(),
  permissions: z.string().optional().nullable(),
  reference_id: z.string().optional().nullable(),
  config_id: z.string().optional().nullable(),
});

export type ApiKey = z.infer<typeof apiKeySchema>;
export type ApiKeyInitializer = z.infer<typeof apiKeyInitializerSchema>;
export type ApiKeyMutator = z.infer<typeof apiKeyMutatorSchema>;
