// Generated by ts-to-zod
import { z } from "zod";

export const backupSettingsSchema = z.object({
  id: z.number().optional(),
  backupEnabled: z.boolean().optional(),
  backupDays: z.array(z.string()).optional(),
  backupTime: z.string().optional(),
  retentionDays: z.number().optional(),
  lastBackupStatus: z.string().nullable().optional(),
  lastBackupTimestamp: z.coerce.date().nullable().optional(),
  backup_enabled: z.boolean().optional(),
  backup_days: z.array(z.string()).optional(),
  backup_time: z.string().optional(),
  retention_days: z.number().optional(),
  last_backup_status: z.string().nullable().optional(),
  last_backup_timestamp: z.coerce.date().nullable().optional(),
  created_at: z.date().optional().nullable(),
  updated_at: z.date().optional().nullable(),
});

export const backupSettingsInitializerSchema = z.object({
  id: z.number().optional(),
  backupEnabled: z.boolean().optional(),
  backupDays: z.array(z.string()).optional(),
  backupTime: z.string().optional(),
  retentionDays: z.number().optional(),
  lastBackupStatus: z.string().optional().nullable(),
  lastBackupTimestamp: z.date().optional().nullable(),
  backup_enabled: z.boolean().optional(),
  backup_days: z.array(z.string()).optional(),
  backup_time: z.string().optional(),
  retention_days: z.number().optional(),
  last_backup_status: z.string().optional().nullable(),
  last_backup_timestamp: z.date().optional().nullable(),
  created_at: z.date().optional().nullable(),
  updated_at: z.date().optional().nullable(),
});

export const backupSettingsMutatorSchema = z.object({
  id: z.number().optional(),
  backupEnabled: z.boolean().optional(),
  backupDays: z.array(z.string()).optional(),
  backupTime: z.string().optional(),
  retentionDays: z.number().optional(),
  lastBackupStatus: z.string().optional().nullable(),
  lastBackupTimestamp: z.date().optional().nullable(),
  backup_enabled: z.boolean().optional(),
  backup_days: z.array(z.string()).optional(),
  backup_time: z.string().optional(),
  retention_days: z.number().optional(),
  last_backup_status: z.string().optional().nullable(),
  last_backup_timestamp: z.date().optional().nullable(),
  created_at: z.date().optional().nullable(),
  updated_at: z.date().optional().nullable(),
});

export type BackupSettings = z.infer<typeof backupSettingsSchema>;
export type BackupSettingsInitializer = z.infer<
  typeof backupSettingsInitializerSchema
>;
export type BackupSettingsMutator = z.infer<typeof backupSettingsMutatorSchema>;
