// Generated by ts-to-zod
import { z } from "zod";

export const customCategoriesSchema = z.object({
  id: z.string(),
  user_id: z.string(),
  name: z.string(),
  measurement_type: z.string(),
  frequency: z.string(),
  created_at: z.coerce.date(),
  updated_at: z.coerce.date(),
  data_type: z.string().nullable(),
  created_by_user_id: z.string().nullable(),
  updated_by_user_id: z.string().nullable(),
  display_name: z.string().nullable(),
});

export const customCategoriesInitializerSchema = z.object({
  id: z.string().optional(),
  user_id: z.string(),
  name: z.string(),
  measurement_type: z.string(),
  frequency: z.string(),
  created_at: z.coerce.date().optional(),
  updated_at: z.coerce.date().optional(),
  data_type: z.string().optional().nullable(),
  created_by_user_id: z.string().optional().nullable(),
  updated_by_user_id: z.string().optional().nullable(),
  display_name: z.string().optional().nullable(),
});

export const customCategoriesMutatorSchema = z.object({
  id: z.string().optional(),
  user_id: z.string().optional(),
  name: z.string().optional(),
  measurement_type: z.string().optional(),
  frequency: z.string().optional(),
  created_at: z.coerce.date().optional(),
  updated_at: z.coerce.date().optional(),
  data_type: z.string().optional().nullable(),
  created_by_user_id: z.string().optional().nullable(),
  updated_by_user_id: z.string().optional().nullable(),
  display_name: z.string().optional().nullable(),
});

export type DatabaseCustomCategories = z.infer<typeof customCategoriesSchema>;
export type DatabaseCustomCategoriesInitializer = z.infer<
  typeof customCategoriesInitializerSchema
>;
export type DatabaseCustomCategoriesMutator = z.infer<
  typeof customCategoriesMutatorSchema
>;
