// Generated by ts-to-zod
import { z } from "zod";

const userIdSchema = z.any();

export const customMeasurementsSchema = z.object({
  id: z.string(),
  user_id: z.string(),
  category_id: z.string(),
  value: z.string(),
  entry_date: z.date(),
  entry_hour: z.number().nullable(),
  entry_timestamp: z.date(),
  created_at: z.date(),
  updated_at: z.date().nullable(),
  notes: z.string().nullable(),
  created_by_user_id: userIdSchema.nullable(),
  updated_by_user_id: userIdSchema.nullable(),
  source: z.string(),
});

export const customMeasurementsInitializerSchema = z.object({
  id: z.string().optional(),
  user_id: z.string(),
  category_id: z.string(),
  value: z.string(),
  entry_date: z.date(),
  entry_hour: z.number().optional().nullable(),
  entry_timestamp: z.date().optional(),
  created_at: z.date().optional(),
  updated_at: z.date().optional().nullable(),
  notes: z.string().optional().nullable(),
  created_by_user_id: userIdSchema.optional().nullable(),
  updated_by_user_id: userIdSchema.optional().nullable(),
  source: z.string().optional(),
});

export const customMeasurementsMutatorSchema = z.object({
  id: z.string().optional(),
  user_id: z.string().optional(),
  category_id: z.string().optional(),
  value: z.string().optional(),
  entry_date: z.date().optional(),
  entry_hour: z.number().optional().nullable(),
  entry_timestamp: z.date().optional(),
  created_at: z.date().optional(),
  updated_at: z.date().optional().nullable(),
  notes: z.string().optional().nullable(),
  created_by_user_id: userIdSchema.optional().nullable(),
  updated_by_user_id: userIdSchema.optional().nullable(),
  source: z.string().optional(),
});

export type DatabaseCustomMeasurements = z.infer<
  typeof customMeasurementsSchema
>;
export type DatabaseCustomMeasurementsInitializer = z.infer<
  typeof customMeasurementsInitializerSchema
>;
export type DatabaseCustomMeasurementsMutator = z.infer<
  typeof customMeasurementsMutatorSchema
>;
