// Generated by ts-to-zod
import { z } from "zod";

export const dailySleepNeedIdSchema = z.string().and(
  z.object({
    __brand: z.literal("public.daily_sleep_need"),
  }),
);

const userIdSchema = z.any();

export const dailySleepNeedSchema = z.object({
  id: dailySleepNeedIdSchema,
  user_id: userIdSchema,
  target_date: z.date(),
  calculated_at: z.date().nullable(),
  baseline_need: z.number(),
  strain_addition: z.number().nullable(),
  debt_addition: z.number().nullable(),
  nap_subtraction: z.number().nullable(),
  total_need: z.number(),
  training_load_score: z.number().nullable(),
  current_debt_hours: z.number().nullable(),
  nap_minutes: z.number().nullable(),
  recovery_score_yesterday: z.number().nullable(),
});

export const dailySleepNeedInitializerSchema = z.object({
  id: dailySleepNeedIdSchema.optional(),
  user_id: userIdSchema,
  target_date: z.date(),
  calculated_at: z.date().optional().nullable(),
  baseline_need: z.number(),
  strain_addition: z.number().optional().nullable(),
  debt_addition: z.number().optional().nullable(),
  nap_subtraction: z.number().optional().nullable(),
  total_need: z.number(),
  training_load_score: z.number().optional().nullable(),
  current_debt_hours: z.number().optional().nullable(),
  nap_minutes: z.number().optional().nullable(),
  recovery_score_yesterday: z.number().optional().nullable(),
});

export const dailySleepNeedMutatorSchema = z.object({
  id: dailySleepNeedIdSchema.optional(),
  user_id: userIdSchema.optional(),
  target_date: z.date().optional(),
  calculated_at: z.date().optional().nullable(),
  baseline_need: z.number().optional(),
  strain_addition: z.number().optional().nullable(),
  debt_addition: z.number().optional().nullable(),
  nap_subtraction: z.number().optional().nullable(),
  total_need: z.number().optional(),
  training_load_score: z.number().optional().nullable(),
  current_debt_hours: z.number().optional().nullable(),
  nap_minutes: z.number().optional().nullable(),
  recovery_score_yesterday: z.number().optional().nullable(),
});

export type DailySleepNeed = z.infer<typeof dailySleepNeedSchema>;
export type DailySleepNeedInitializer = z.infer<
  typeof dailySleepNeedInitializerSchema
>;
export type DailySleepNeedMutator = z.infer<typeof dailySleepNeedMutatorSchema>;
