// Generated by ts-to-zod
import { z } from "zod";

export const dayClassificationCacheIdSchema = z.string().and(
  z.object({
    __brand: z.literal("public.day_classification_cache"),
  }),
);

const userIdSchema = z.any();

export const dayClassificationCacheSchema = z.object({
  id: dayClassificationCacheIdSchema,
  user_id: userIdSchema,
  day_of_week: z.number(),
  classified_as: z.string(),
  mean_wake_hour: z.number().nullable(),
  variance_minutes: z.number().nullable(),
  sample_count: z.number().nullable(),
  last_updated: z.date().nullable(),
});

export const dayClassificationCacheInitializerSchema = z.object({
  id: dayClassificationCacheIdSchema.optional(),
  user_id: userIdSchema,
  day_of_week: z.number(),
  classified_as: z.string(),
  mean_wake_hour: z.number().optional().nullable(),
  variance_minutes: z.number().optional().nullable(),
  sample_count: z.number().optional().nullable(),
  last_updated: z.date().optional().nullable(),
});

export const dayClassificationCacheMutatorSchema = z.object({
  id: dayClassificationCacheIdSchema.optional(),
  user_id: userIdSchema.optional(),
  day_of_week: z.number().optional(),
  classified_as: z.string().optional(),
  mean_wake_hour: z.number().optional().nullable(),
  variance_minutes: z.number().optional().nullable(),
  sample_count: z.number().optional().nullable(),
  last_updated: z.date().optional().nullable(),
});

export type DayClassificationCache = z.infer<
  typeof dayClassificationCacheSchema
>;
export type DayClassificationCacheInitializer = z.infer<
  typeof dayClassificationCacheInitializerSchema
>;
export type DayClassificationCacheMutator = z.infer<
  typeof dayClassificationCacheMutatorSchema
>;
