// Generated by ts-to-zod
import { z } from "zod";

export const exercisePresetEntriesIdSchema = z.string().and(
  z.object({
    __brand: z.literal("public.exercise_preset_entries"),
  }),
);

const userIdSchema = z.any();

const workoutPresetsIdSchema = z.any();

export const exercisePresetEntriesSchema = z.object({
  id: exercisePresetEntriesIdSchema,
  user_id: userIdSchema,
  workout_preset_id: workoutPresetsIdSchema.nullable(),
  name: z.string(),
  description: z.string().nullable(),
  entry_date: z.date(),
  created_at: z.date().nullable(),
  updated_at: z.date().nullable(),
  created_by_user_id: userIdSchema.nullable(),
  notes: z.string().nullable(),
  source: z.string(),
});

export const exercisePresetEntriesInitializerSchema = z.object({
  id: exercisePresetEntriesIdSchema.optional(),
  user_id: userIdSchema,
  workout_preset_id: workoutPresetsIdSchema.optional().nullable(),
  name: z.string(),
  description: z.string().optional().nullable(),
  entry_date: z.date(),
  created_at: z.date().optional().nullable(),
  updated_at: z.date().optional().nullable(),
  created_by_user_id: userIdSchema.optional().nullable(),
  notes: z.string().optional().nullable(),
  source: z.string().optional(),
});

export const exercisePresetEntriesMutatorSchema = z.object({
  id: exercisePresetEntriesIdSchema.optional(),
  user_id: userIdSchema.optional(),
  workout_preset_id: workoutPresetsIdSchema.optional().nullable(),
  name: z.string().optional(),
  description: z.string().optional().nullable(),
  entry_date: z.date().optional(),
  created_at: z.date().optional().nullable(),
  updated_at: z.date().optional().nullable(),
  created_by_user_id: userIdSchema.optional().nullable(),
  notes: z.string().optional().nullable(),
  source: z.string().optional(),
});

export type ExercisePresetEntries = z.infer<typeof exercisePresetEntriesSchema>;
export type ExercisePresetEntriesInitializer = z.infer<
  typeof exercisePresetEntriesInitializerSchema
>;
export type ExercisePresetEntriesMutator = z.infer<
  typeof exercisePresetEntriesMutatorSchema
>;
