// Generated by ts-to-zod
import { z } from "zod";

export const exerciseEntryActivityDetailsIdSchema = z.string().and(
  z.object({
    __brand: z.literal("public.exercise_entry_activity_details"),
  }),
);

const exerciseEntriesIdSchema = z.any();

const userIdSchema = z.any();

const exercisePresetEntriesIdSchema = z.any();

export const exerciseEntryActivityDetailsSchema = z.object({
  id: exerciseEntryActivityDetailsIdSchema,
  exercise_entry_id: exerciseEntriesIdSchema.nullable(),
  provider_name: z.string(),
  detail_type: z.string(),
  detail_data: z.unknown(),
  created_at: z.date().nullable(),
  updated_at: z.date().nullable(),
  created_by_user_id: userIdSchema.nullable(),
  updated_by_user_id: userIdSchema.nullable(),
  exercise_preset_entry_id: exercisePresetEntriesIdSchema.nullable(),
});

export const exerciseEntryActivityDetailsInitializerSchema = z.object({
  id: exerciseEntryActivityDetailsIdSchema.optional(),
  exercise_entry_id: exerciseEntriesIdSchema.optional().nullable(),
  provider_name: z.string(),
  detail_type: z.string(),
  detail_data: z.unknown(),
  created_at: z.date().optional().nullable(),
  updated_at: z.date().optional().nullable(),
  created_by_user_id: userIdSchema.optional().nullable(),
  updated_by_user_id: userIdSchema.optional().nullable(),
  exercise_preset_entry_id: exercisePresetEntriesIdSchema.optional().nullable(),
});

export const exerciseEntryActivityDetailsMutatorSchema = z.object({
  id: exerciseEntryActivityDetailsIdSchema.optional(),
  exercise_entry_id: exerciseEntriesIdSchema.optional().nullable(),
  provider_name: z.string().optional(),
  detail_type: z.string().optional(),
  detail_data: z.unknown().optional(),
  created_at: z.date().optional().nullable(),
  updated_at: z.date().optional().nullable(),
  created_by_user_id: userIdSchema.optional().nullable(),
  updated_by_user_id: userIdSchema.optional().nullable(),
  exercise_preset_entry_id: exercisePresetEntriesIdSchema.optional().nullable(),
});

export type ExerciseEntryActivityDetails = z.infer<
  typeof exerciseEntryActivityDetailsSchema
>;
export type ExerciseEntryActivityDetailsInitializer = z.infer<
  typeof exerciseEntryActivityDetailsInitializerSchema
>;
export type ExerciseEntryActivityDetailsMutator = z.infer<
  typeof exerciseEntryActivityDetailsMutatorSchema
>;
