// Generated by ts-to-zod
import { z } from "zod";

const userIdSchema = z.any();

export const familyAccessSchema = z.object({
  id: z.string(),
  owner_user_id: userIdSchema,
  family_user_id: userIdSchema,
  family_email: z.string(),
  access_permissions: z.unknown(),
  access_start_date: z.date(),
  access_end_date: z.date().nullable(),
  is_active: z.boolean(),
  created_at: z.date(),
  updated_at: z.date(),
  status: z.string().nullable(),
});

export const familyAccessInitializerSchema = z.object({
  id: z.string().optional(),
  owner_user_id: userIdSchema,
  family_user_id: userIdSchema,
  family_email: z.string(),
  access_permissions: z.unknown().optional(),
  access_start_date: z.date().optional(),
  access_end_date: z.date().optional().nullable(),
  is_active: z.boolean().optional(),
  created_at: z.date().optional(),
  updated_at: z.date().optional(),
  status: z.string().optional().nullable(),
});

export const familyAccessMutatorSchema = z.object({
  id: z.string().optional(),
  owner_user_id: userIdSchema.optional(),
  family_user_id: userIdSchema.optional(),
  family_email: z.string().optional(),
  access_permissions: z.unknown().optional(),
  access_start_date: z.date().optional(),
  access_end_date: z.date().optional().nullable(),
  is_active: z.boolean().optional(),
  created_at: z.date().optional(),
  updated_at: z.date().optional(),
  status: z.string().optional().nullable(),
});

export type FamilyAccess = z.infer<typeof familyAccessSchema>;
export type FamilyAccessInitializer = z.infer<
  typeof familyAccessInitializerSchema
>;
export type FamilyAccessMutator = z.infer<typeof familyAccessMutatorSchema>;
