// Generated by ts-to-zod
import { z } from "zod";

export const fastingLogsIdSchema = z.string().and(
  z.object({
    __brand: z.literal("public.fasting_logs"),
  }),
);

const userIdSchema = z.any();

export const fastingLogsSchema = z.object({
  id: fastingLogsIdSchema,
  user_id: userIdSchema,
  start_time: z.date(),
  end_time: z.date().nullable(),
  target_end_time: z.date().nullable(),
  duration_minutes: z.number().nullable(),
  fasting_type: z.string().nullable(),
  status: z.string().nullable(),
  created_at: z.date().nullable(),
  updated_at: z.date().nullable(),
});

export const fastingLogsInitializerSchema = z.object({
  id: fastingLogsIdSchema.optional(),
  user_id: userIdSchema,
  start_time: z.date(),
  end_time: z.date().optional().nullable(),
  target_end_time: z.date().optional().nullable(),
  duration_minutes: z.number().optional().nullable(),
  fasting_type: z.string().optional().nullable(),
  status: z.string().optional().nullable(),
  created_at: z.date().optional().nullable(),
  updated_at: z.date().optional().nullable(),
});

export const fastingLogsMutatorSchema = z.object({
  id: fastingLogsIdSchema.optional(),
  user_id: userIdSchema.optional(),
  start_time: z.date().optional(),
  end_time: z.date().optional().nullable(),
  target_end_time: z.date().optional().nullable(),
  duration_minutes: z.number().optional().nullable(),
  fasting_type: z.string().optional().nullable(),
  status: z.string().optional().nullable(),
  created_at: z.date().optional().nullable(),
  updated_at: z.date().optional().nullable(),
});

export type FastingLogs = z.infer<typeof fastingLogsSchema>;
export type FastingLogsInitializer = z.infer<
  typeof fastingLogsInitializerSchema
>;
export type FastingLogsMutator = z.infer<typeof fastingLogsMutatorSchema>;
