// Generated by ts-to-zod
import { z } from "zod";

export const mealPlanTemplatesIdSchema = z.string().and(
  z.object({
    __brand: z.literal("public.meal_plan_templates"),
  }),
);

const userIdSchema = z.any();

export const mealPlanTemplatesSchema = z.object({
  id: mealPlanTemplatesIdSchema,
  user_id: userIdSchema,
  plan_name: z.string(),
  description: z.string().nullable(),
  start_date: z.date(),
  end_date: z.date().nullable(),
  is_active: z.boolean(),
  created_at: z.date(),
  updated_at: z.date(),
});

export const mealPlanTemplatesInitializerSchema = z.object({
  id: mealPlanTemplatesIdSchema.optional(),
  user_id: userIdSchema,
  plan_name: z.string(),
  description: z.string().optional().nullable(),
  start_date: z.date(),
  end_date: z.date().optional().nullable(),
  is_active: z.boolean().optional(),
  created_at: z.date().optional(),
  updated_at: z.date().optional(),
});

export const mealPlanTemplatesMutatorSchema = z.object({
  id: mealPlanTemplatesIdSchema.optional(),
  user_id: userIdSchema.optional(),
  plan_name: z.string().optional(),
  description: z.string().optional().nullable(),
  start_date: z.date().optional(),
  end_date: z.date().optional().nullable(),
  is_active: z.boolean().optional(),
  created_at: z.date().optional(),
  updated_at: z.date().optional(),
});

export type MealPlanTemplates = z.infer<typeof mealPlanTemplatesSchema>;
export type MealPlanTemplatesInitializer = z.infer<
  typeof mealPlanTemplatesInitializerSchema
>;
export type MealPlanTemplatesMutator = z.infer<
  typeof mealPlanTemplatesMutatorSchema
>;
