// Generated by ts-to-zod
import { z } from "zod";

export const mealPlansIdSchema = z.string().and(
  z.object({
    __brand: z.literal("public.meal_plans"),
  }),
);

const userIdSchema = z.any();

const mealsIdSchema = z.any();

const foodsIdSchema = z.any();

const foodVariantsIdSchema = z.any();

const mealTypesIdSchema = z.any();

export const mealPlansSchema = z.object({
  id: mealPlansIdSchema,
  user_id: userIdSchema,
  meal_id: mealsIdSchema.nullable(),
  food_id: foodsIdSchema.nullable(),
  variant_id: foodVariantsIdSchema.nullable(),
  quantity: z.number().nullable(),
  unit: z.string().nullable(),
  plan_date: z.date(),
  is_template: z.boolean().nullable(),
  template_name: z.string().nullable(),
  day_of_week: z.number().nullable(),
  created_at: z.date(),
  updated_at: z.date(),
  meal_type_id: mealTypesIdSchema,
});

export const mealPlansInitializerSchema = z.object({
  id: mealPlansIdSchema.optional(),
  user_id: userIdSchema,
  meal_id: mealsIdSchema.optional().nullable(),
  food_id: foodsIdSchema.optional().nullable(),
  variant_id: foodVariantsIdSchema.optional().nullable(),
  quantity: z.number().optional().nullable(),
  unit: z.string().optional().nullable(),
  plan_date: z.date(),
  is_template: z.boolean().optional().nullable(),
  template_name: z.string().optional().nullable(),
  day_of_week: z.number().optional().nullable(),
  created_at: z.date().optional(),
  updated_at: z.date().optional(),
  meal_type_id: mealTypesIdSchema,
});

export const mealPlansMutatorSchema = z.object({
  id: mealPlansIdSchema.optional(),
  user_id: userIdSchema.optional(),
  meal_id: mealsIdSchema.optional().nullable(),
  food_id: foodsIdSchema.optional().nullable(),
  variant_id: foodVariantsIdSchema.optional().nullable(),
  quantity: z.number().optional().nullable(),
  unit: z.string().optional().nullable(),
  plan_date: z.date().optional(),
  is_template: z.boolean().optional().nullable(),
  template_name: z.string().optional().nullable(),
  day_of_week: z.number().optional().nullable(),
  created_at: z.date().optional(),
  updated_at: z.date().optional(),
  meal_type_id: mealTypesIdSchema.optional(),
});

export type MealPlans = z.infer<typeof mealPlansSchema>;
export type MealPlansInitializer = z.infer<typeof mealPlansInitializerSchema>;
export type MealPlansMutator = z.infer<typeof mealPlansMutatorSchema>;
