// Generated by ts-to-zod
import { z } from "zod";

export const mealPlanTemplateAssignmentsIdSchema = z.string().and(
  z.object({
    __brand: z.literal("public.meal_plan_template_assignments"),
  }),
);

const mealPlanTemplatesIdSchema = z.any();

const mealsIdSchema = z.any();

const foodsIdSchema = z.any();

const foodVariantsIdSchema = z.any();

const mealTypesIdSchema = z.any();

export const mealPlanTemplateAssignmentsSchema = z.object({
  id: mealPlanTemplateAssignmentsIdSchema,
  template_id: mealPlanTemplatesIdSchema,
  day_of_week: z.number(),
  meal_id: mealsIdSchema.nullable(),
  item_type: z.string(),
  food_id: foodsIdSchema.nullable(),
  variant_id: foodVariantsIdSchema.nullable(),
  quantity: z.number().nullable(),
  unit: z.string().nullable(),
  meal_type_id: mealTypesIdSchema,
});

export const mealPlanTemplateAssignmentsInitializerSchema = z.object({
  id: mealPlanTemplateAssignmentsIdSchema.optional(),
  template_id: mealPlanTemplatesIdSchema,
  day_of_week: z.number(),
  meal_id: mealsIdSchema.optional().nullable(),
  item_type: z.string().optional(),
  food_id: foodsIdSchema.optional().nullable(),
  variant_id: foodVariantsIdSchema.optional().nullable(),
  quantity: z.number().optional().nullable(),
  unit: z.string().optional().nullable(),
  meal_type_id: mealTypesIdSchema,
});

export const mealPlanTemplateAssignmentsMutatorSchema = z.object({
  id: mealPlanTemplateAssignmentsIdSchema.optional(),
  template_id: mealPlanTemplatesIdSchema.optional(),
  day_of_week: z.number().optional(),
  meal_id: mealsIdSchema.optional().nullable(),
  item_type: z.string().optional(),
  food_id: foodsIdSchema.optional().nullable(),
  variant_id: foodVariantsIdSchema.optional().nullable(),
  quantity: z.number().optional().nullable(),
  unit: z.string().optional().nullable(),
  meal_type_id: mealTypesIdSchema.optional(),
});

export type MealPlanTemplateAssignments = z.infer<
  typeof mealPlanTemplateAssignmentsSchema
>;
export type MealPlanTemplateAssignmentsInitializer = z.infer<
  typeof mealPlanTemplateAssignmentsInitializerSchema
>;
export type MealPlanTemplateAssignmentsMutator = z.infer<
  typeof mealPlanTemplateAssignmentsMutatorSchema
>;
