// Generated by ts-to-zod
import { z } from "zod";

export const oidcProvidersIdSchema = z.number().and(
  z.object({
    __brand: z.literal("public.oidc_providers"),
  }),
);

export const oidcProvidersSchema = z.object({
  id: oidcProvidersIdSchema,
  issuer_url: z.string(),
  client_id: z.string(),
  encrypted_client_secret: z.string().nullable(),
  client_secret_iv: z.string().nullable(),
  client_secret_tag: z.string().nullable(),
  redirect_uris: z.array(z.string()),
  scope: z.string(),
  token_endpoint_auth_method: z.string(),
  response_types: z.array(z.string()),
  is_active: z.boolean(),
  auto_register: z.boolean(),
  display_name: z.string().nullable(),
  logo_url: z.string().nullable(),
  created_at: z.date().nullable(),
  updated_at: z.date().nullable(),
  signing_algorithm: z.string().nullable(),
  profile_signing_algorithm: z.string().nullable(),
  timeout: z.number().nullable(),
});

export const oidcProvidersInitializerSchema = z.object({
  id: oidcProvidersIdSchema.optional(),
  issuer_url: z.string(),
  client_id: z.string(),
  encrypted_client_secret: z.string().optional().nullable(),
  client_secret_iv: z.string().optional().nullable(),
  client_secret_tag: z.string().optional().nullable(),
  redirect_uris: z.array(z.string()),
  scope: z.string(),
  token_endpoint_auth_method: z.string().optional(),
  response_types: z.array(z.string()).optional(),
  is_active: z.boolean().optional(),
  auto_register: z.boolean().optional(),
  display_name: z.string().optional().nullable(),
  logo_url: z.string().optional().nullable(),
  created_at: z.date().optional().nullable(),
  updated_at: z.date().optional().nullable(),
  signing_algorithm: z.string().optional().nullable(),
  profile_signing_algorithm: z.string().optional().nullable(),
  timeout: z.number().optional().nullable(),
});

export const oidcProvidersMutatorSchema = z.object({
  id: oidcProvidersIdSchema.optional(),
  issuer_url: z.string().optional(),
  client_id: z.string().optional(),
  encrypted_client_secret: z.string().optional().nullable(),
  client_secret_iv: z.string().optional().nullable(),
  client_secret_tag: z.string().optional().nullable(),
  redirect_uris: z.array(z.string()).optional(),
  scope: z.string().optional(),
  token_endpoint_auth_method: z.string().optional(),
  response_types: z.array(z.string()).optional(),
  is_active: z.boolean().optional(),
  auto_register: z.boolean().optional(),
  display_name: z.string().optional().nullable(),
  logo_url: z.string().optional().nullable(),
  created_at: z.date().optional().nullable(),
  updated_at: z.date().optional().nullable(),
  signing_algorithm: z.string().optional().nullable(),
  profile_signing_algorithm: z.string().optional().nullable(),
  timeout: z.number().optional().nullable(),
});

export type OidcProviders = z.infer<typeof oidcProvidersSchema>;
export type OidcProvidersInitializer = z.infer<
  typeof oidcProvidersInitializerSchema
>;
export type OidcProvidersMutator = z.infer<typeof oidcProvidersMutatorSchema>;
