// Generated by ts-to-zod
import { z } from "zod";

export const onboardingDataIdSchema = z.string().and(
  z.object({
    __brand: z.literal("public.onboarding_data"),
  }),
);

const userIdSchema = z.any();

export const onboardingDataSchema = z.object({
  id: onboardingDataIdSchema,
  user_id: userIdSchema,
  sex: z.string().nullable(),
  primary_goal: z.string().nullable(),
  current_weight: z.number().nullable(),
  height: z.number().nullable(),
  birth_date: z.date().nullable(),
  body_fat_range: z.string().nullable(),
  target_weight: z.number().nullable(),
  meals_per_day: z.number().nullable(),
  activity_level: z.string().nullable(),
  add_burned_calories: z.boolean().nullable(),
  created_at: z.date().nullable(),
});

export const onboardingDataInitializerSchema = z.object({
  id: onboardingDataIdSchema.optional(),
  user_id: userIdSchema,
  sex: z.string().optional().nullable(),
  primary_goal: z.string().optional().nullable(),
  current_weight: z.number().optional().nullable(),
  height: z.number().optional().nullable(),
  birth_date: z.date().optional().nullable(),
  body_fat_range: z.string().optional().nullable(),
  target_weight: z.number().optional().nullable(),
  meals_per_day: z.number().optional().nullable(),
  activity_level: z.string().optional().nullable(),
  add_burned_calories: z.boolean().optional().nullable(),
  created_at: z.date().optional().nullable(),
});

export const onboardingDataMutatorSchema = z.object({
  id: onboardingDataIdSchema.optional(),
  user_id: userIdSchema.optional(),
  sex: z.string().optional().nullable(),
  primary_goal: z.string().optional().nullable(),
  current_weight: z.number().optional().nullable(),
  height: z.number().optional().nullable(),
  birth_date: z.date().optional().nullable(),
  body_fat_range: z.string().optional().nullable(),
  target_weight: z.number().optional().nullable(),
  meals_per_day: z.number().optional().nullable(),
  activity_level: z.string().optional().nullable(),
  add_burned_calories: z.boolean().optional().nullable(),
  created_at: z.date().optional().nullable(),
});

export type OnboardingData = z.infer<typeof onboardingDataSchema>;
export type OnboardingDataInitializer = z.infer<
  typeof onboardingDataInitializerSchema
>;
export type OnboardingDataMutator = z.infer<typeof onboardingDataMutatorSchema>;
