// Generated by ts-to-zod
import { z } from "zod";

export const openfoodfactsProductReadRateLimitSchema = z.object({
  id: z.number().int(),
  next_product_read_at: z.date(),
  reservation_token: z.string().uuid().nullable(),
  reservation_expires_at: z.date().nullable(),
  updated_at: z.date(),
});

export const openfoodfactsProductReadRateLimitInitializerSchema =
  openfoodfactsProductReadRateLimitSchema.partial();

export const openfoodfactsProductReadRateLimitMutatorSchema =
  openfoodfactsProductReadRateLimitSchema.partial();

export type OpenFoodFactsProductReadRateLimit = z.infer<
  typeof openfoodfactsProductReadRateLimitSchema
>;
export type OpenFoodFactsProductReadRateLimitInitializer = z.infer<
  typeof openfoodfactsProductReadRateLimitInitializerSchema
>;
export type OpenFoodFactsProductReadRateLimitMutator = z.infer<
  typeof openfoodfactsProductReadRateLimitMutatorSchema
>;
