// Generated by ts-to-zod
import { z } from "zod";

const foodsIdSchema = z.any();

export const openfoodfactsSyncQueueSchema = z.object({
  food_id: foodsIdSchema,
  user_id: z.string(),
  revision: z.number().int(),
  status: z.enum(["pending", "processing", "failed", "succeeded"]),
  attempt_count: z.number().int(),
  next_attempt_at: z.date(),
  lease_expires_at: z.date().nullable(),
  last_error: z.string().nullable(),
  last_succeeded_at: z.date().nullable(),
  created_at: z.date(),
  updated_at: z.date(),
});

export const openfoodfactsSyncQueueInitializerSchema =
  openfoodfactsSyncQueueSchema.partial().required({
    food_id: true,
    user_id: true,
  });

export const openfoodfactsSyncQueueMutatorSchema =
  openfoodfactsSyncQueueSchema.partial();

export type OpenFoodFactsSyncQueue = z.infer<
  typeof openfoodfactsSyncQueueSchema
>;
export type OpenFoodFactsSyncQueueInitializer = z.infer<
  typeof openfoodfactsSyncQueueInitializerSchema
>;
export type OpenFoodFactsSyncQueueMutator = z.infer<
  typeof openfoodfactsSyncQueueMutatorSchema
>;
