// Generated by ts-to-zod
import { z } from "zod";

export const passkeyIdSchema = z.string().and(
  z.object({
    __brand: z.literal("public.passkey"),
  }),
);

const userIdSchema = z.any();

export const passkeySchema = z.object({
  id: passkeyIdSchema,
  name: z.string().nullable(),
  public_key: z.string(),
  user_id: userIdSchema,
  credential_id: z.string(),
  counter: z.number(),
  device_type: z.string(),
  backed_up: z.boolean(),
  transports: z.string().nullable(),
  created_at: z.date().nullable(),
  aaguid: z.string().nullable(),
});

export const passkeyInitializerSchema = z.object({
  id: passkeyIdSchema,
  name: z.string().optional().nullable(),
  public_key: z.string(),
  user_id: userIdSchema,
  credential_id: z.string(),
  counter: z.number(),
  device_type: z.string(),
  backed_up: z.boolean(),
  transports: z.string().optional().nullable(),
  created_at: z.date().optional().nullable(),
  aaguid: z.string().optional().nullable(),
});

export const passkeyMutatorSchema = z.object({
  id: passkeyIdSchema.optional(),
  name: z.string().optional().nullable(),
  public_key: z.string().optional(),
  user_id: userIdSchema.optional(),
  credential_id: z.string().optional(),
  counter: z.number().optional(),
  device_type: z.string().optional(),
  backed_up: z.boolean().optional(),
  transports: z.string().optional().nullable(),
  created_at: z.date().optional().nullable(),
  aaguid: z.string().optional().nullable(),
});

export type Passkey = z.infer<typeof passkeySchema>;
export type PasskeyInitializer = z.infer<typeof passkeyInitializerSchema>;
export type PasskeyMutator = z.infer<typeof passkeyMutatorSchema>;
