// Generated by ts-to-zod
import { z } from "zod";

const userIdSchema = z.any();

export const profilesSchema = z.object({
  id: userIdSchema,
  full_name: z.string().nullable(),
  avatar_url: z.string().nullable(),
  created_at: z.date().nullable(),
  updated_at: z.date().nullable(),
  date_of_birth: z.date().nullable(),
  phone: z.string().nullable(),
  bio: z.string().nullable(),
  phone_number: z.string().nullable(),
  gender: z.string().nullable(),
  sleep_need_method: z.string().nullable(),
  sleep_need_confidence: z.string().nullable(),
  sleep_need_based_on_days: z.number().nullable(),
  sleep_need_last_calculated: z.date().nullable(),
  sd_workday_hours: z.number().nullable(),
  sd_freeday_hours: z.number().nullable(),
  baseline_sleep_need: z.number().nullable(),
  social_jetlag_hours: z.number().nullable(),
});

export const profilesInitializerSchema = z.object({
  id: userIdSchema,
  full_name: z.string().optional().nullable(),
  avatar_url: z.string().optional().nullable(),
  created_at: z.date().optional().nullable(),
  updated_at: z.date().optional().nullable(),
  date_of_birth: z.date().optional().nullable(),
  phone: z.string().optional().nullable(),
  bio: z.string().optional().nullable(),
  phone_number: z.string().optional().nullable(),
  gender: z.string().optional().nullable(),
  sleep_need_method: z.string().optional().nullable(),
  sleep_need_confidence: z.string().optional().nullable(),
  sleep_need_based_on_days: z.number().optional().nullable(),
  sleep_need_last_calculated: z.date().optional().nullable(),
  sd_workday_hours: z.number().optional().nullable(),
  sd_freeday_hours: z.number().optional().nullable(),
  baseline_sleep_need: z.number().optional().nullable(),
  social_jetlag_hours: z.number().optional().nullable(),
});

export const profilesMutatorSchema = z.object({
  id: userIdSchema.optional(),
  full_name: z.string().optional().nullable(),
  avatar_url: z.string().optional().nullable(),
  created_at: z.date().optional().nullable(),
  updated_at: z.date().optional().nullable(),
  date_of_birth: z.date().optional().nullable(),
  phone: z.string().optional().nullable(),
  bio: z.string().optional().nullable(),
  phone_number: z.string().optional().nullable(),
  gender: z.string().optional().nullable(),
  sleep_need_method: z.string().optional().nullable(),
  sleep_need_confidence: z.string().optional().nullable(),
  sleep_need_based_on_days: z.number().optional().nullable(),
  sleep_need_last_calculated: z.date().optional().nullable(),
  sd_workday_hours: z.number().optional().nullable(),
  sd_freeday_hours: z.number().optional().nullable(),
  baseline_sleep_need: z.number().optional().nullable(),
  social_jetlag_hours: z.number().optional().nullable(),
});

export type Profiles = z.infer<typeof profilesSchema>;
export type ProfilesInitializer = z.infer<typeof profilesInitializerSchema>;
export type ProfilesMutator = z.infer<typeof profilesMutatorSchema>;
