// Generated by ts-to-zod
import { z } from "zod";

export const sessionIdSchema = z.string().and(
  z.object({
    __brand: z.literal("public.session"),
  }),
);

const userIdSchema = z.any();

export const sessionSchema = z.object({
  id: sessionIdSchema,
  expires_at: z.date(),
  token: z.string(),
  created_at: z.date(),
  updated_at: z.date(),
  ip_address: z.string().nullable(),
  user_agent: z.string().nullable(),
  impersonated_by: z.string().nullable(),
  user_id: userIdSchema,
});

export const sessionInitializerSchema = z.object({
  id: sessionIdSchema.optional(),
  expires_at: z.date(),
  token: z.string(),
  created_at: z.date().optional(),
  updated_at: z.date().optional(),
  ip_address: z.string().optional().nullable(),
  user_agent: z.string().optional().nullable(),
  impersonated_by: z.string().optional().nullable(),
  user_id: userIdSchema,
});

export const sessionMutatorSchema = z.object({
  id: sessionIdSchema.optional(),
  expires_at: z.date().optional(),
  token: z.string().optional(),
  created_at: z.date().optional(),
  updated_at: z.date().optional(),
  ip_address: z.string().optional().nullable(),
  user_agent: z.string().optional().nullable(),
  impersonated_by: z.string().optional().nullable(),
  user_id: userIdSchema.optional(),
});

export type Session = z.infer<typeof sessionSchema>;
export type SessionInitializer = z.infer<typeof sessionInitializerSchema>;
export type SessionMutator = z.infer<typeof sessionMutatorSchema>;
