// Generated by ts-to-zod
import { z } from "zod";

export const sleepNeedCalculationsIdSchema = z.string().and(
  z.object({
    __brand: z.literal("public.sleep_need_calculations"),
  }),
);

const userIdSchema = z.any();

export const sleepNeedCalculationsSchema = z.object({
  id: sleepNeedCalculationsIdSchema,
  user_id: userIdSchema,
  calculated_at: z.date().nullable(),
  method: z.string(),
  calculated_need: z.number(),
  confidence: z.string(),
  based_on_days: z.number(),
  sd_workday: z.number().nullable(),
  sd_freeday: z.number().nullable(),
  sd_week: z.number().nullable(),
  social_jetlag_hours: z.number().nullable(),
  mid_sleep_workday: z.date().nullable(),
  mid_sleep_freeday: z.date().nullable(),
  mid_sleep_corrected: z.date().nullable(),
  workdays_count: z.number().nullable(),
  freedays_count: z.number().nullable(),
  data_start_date: z.date().nullable(),
  data_end_date: z.date().nullable(),
});

export const sleepNeedCalculationsInitializerSchema = z.object({
  id: sleepNeedCalculationsIdSchema.optional(),
  user_id: userIdSchema,
  calculated_at: z.date().optional().nullable(),
  method: z.string(),
  calculated_need: z.number(),
  confidence: z.string(),
  based_on_days: z.number(),
  sd_workday: z.number().optional().nullable(),
  sd_freeday: z.number().optional().nullable(),
  sd_week: z.number().optional().nullable(),
  social_jetlag_hours: z.number().optional().nullable(),
  mid_sleep_workday: z.date().optional().nullable(),
  mid_sleep_freeday: z.date().optional().nullable(),
  mid_sleep_corrected: z.date().optional().nullable(),
  workdays_count: z.number().optional().nullable(),
  freedays_count: z.number().optional().nullable(),
  data_start_date: z.date().optional().nullable(),
  data_end_date: z.date().optional().nullable(),
});

export const sleepNeedCalculationsMutatorSchema = z.object({
  id: sleepNeedCalculationsIdSchema.optional(),
  user_id: userIdSchema.optional(),
  calculated_at: z.date().optional().nullable(),
  method: z.string().optional(),
  calculated_need: z.number().optional(),
  confidence: z.string().optional(),
  based_on_days: z.number().optional(),
  sd_workday: z.number().optional().nullable(),
  sd_freeday: z.number().optional().nullable(),
  sd_week: z.number().optional().nullable(),
  social_jetlag_hours: z.number().optional().nullable(),
  mid_sleep_workday: z.date().optional().nullable(),
  mid_sleep_freeday: z.date().optional().nullable(),
  mid_sleep_corrected: z.date().optional().nullable(),
  workdays_count: z.number().optional().nullable(),
  freedays_count: z.number().optional().nullable(),
  data_start_date: z.date().optional().nullable(),
  data_end_date: z.date().optional().nullable(),
});

export type SleepNeedCalculations = z.infer<typeof sleepNeedCalculationsSchema>;
export type SleepNeedCalculationsInitializer = z.infer<
  typeof sleepNeedCalculationsInitializerSchema
>;
export type SleepNeedCalculationsMutator = z.infer<
  typeof sleepNeedCalculationsMutatorSchema
>;
