// Generated by ts-to-zod
import { z } from "zod";

export const sleepEntryStagesIdSchema = z.string().and(
  z.object({
    __brand: z.literal("public.sleep_entry_stages"),
  }),
);

const sleepEntriesIdSchema = z.any();

const userIdSchema = z.any();

export const sleepEntryStagesSchema = z.object({
  id: sleepEntryStagesIdSchema,
  entry_id: sleepEntriesIdSchema,
  user_id: userIdSchema,
  stage_type: z.string(),
  start_time: z.date(),
  end_time: z.date(),
  duration_in_seconds: z.number(),
  created_at: z.date().nullable(),
  updated_at: z.date().nullable(),
  created_by_user_id: userIdSchema.nullable(),
  updated_by_user_id: userIdSchema.nullable(),
});

export const sleepEntryStagesInitializerSchema = z.object({
  id: sleepEntryStagesIdSchema.optional(),
  entry_id: sleepEntriesIdSchema,
  user_id: userIdSchema,
  stage_type: z.string(),
  start_time: z.date(),
  end_time: z.date(),
  duration_in_seconds: z.number(),
  created_at: z.date().optional().nullable(),
  updated_at: z.date().optional().nullable(),
  created_by_user_id: userIdSchema.optional().nullable(),
  updated_by_user_id: userIdSchema.optional().nullable(),
});

export const sleepEntryStagesMutatorSchema = z.object({
  id: sleepEntryStagesIdSchema.optional(),
  entry_id: sleepEntriesIdSchema.optional(),
  user_id: userIdSchema.optional(),
  stage_type: z.string().optional(),
  start_time: z.date().optional(),
  end_time: z.date().optional(),
  duration_in_seconds: z.number().optional(),
  created_at: z.date().optional().nullable(),
  updated_at: z.date().optional().nullable(),
  created_by_user_id: userIdSchema.optional().nullable(),
  updated_by_user_id: userIdSchema.optional().nullable(),
});

export type SleepEntryStages = z.infer<typeof sleepEntryStagesSchema>;
export type SleepEntryStagesInitializer = z.infer<
  typeof sleepEntryStagesInitializerSchema
>;
export type SleepEntryStagesMutator = z.infer<
  typeof sleepEntryStagesMutatorSchema
>;
