// Generated by ts-to-zod
import { z } from "zod";

export const ssoProviderIdSchema = z.string().and(
  z.object({
    __brand: z.literal("public.sso_provider"),
  }),
);

export const ssoProviderSchema = z.object({
  id: ssoProviderIdSchema,
  provider_id: z.string(),
  issuer: z.string(),
  client_id: z.string().nullable(),
  client_secret: z.string().nullable(),
  discovery_endpoint: z.string().nullable(),
  authorization_endpoint: z.string().nullable(),
  token_endpoint: z.string().nullable(),
  jwks_endpoint: z.string().nullable(),
  userinfo_endpoint: z.string().nullable(),
  scopes: z.string().nullable(),
  additional_config: z.string().nullable(),
  domain: z.string(),
  created_at: z.date(),
  updated_at: z.date(),
  oidc_config: z.unknown().nullable(),
  saml_config: z.string().nullable(),
  user_id: z.string().nullable(),
  organization_id: z.string().nullable(),
});

export const ssoProviderInitializerSchema = z.object({
  id: ssoProviderIdSchema.optional(),
  provider_id: z.string(),
  issuer: z.string(),
  client_id: z.string().optional().nullable(),
  client_secret: z.string().optional().nullable(),
  discovery_endpoint: z.string().optional().nullable(),
  authorization_endpoint: z.string().optional().nullable(),
  token_endpoint: z.string().optional().nullable(),
  jwks_endpoint: z.string().optional().nullable(),
  userinfo_endpoint: z.string().optional().nullable(),
  scopes: z.string().optional().nullable(),
  additional_config: z.string().optional().nullable(),
  domain: z.string().optional(),
  created_at: z.date().optional(),
  updated_at: z.date().optional(),
  oidc_config: z.unknown().optional().nullable(),
  saml_config: z.string().optional().nullable(),
  user_id: z.string().optional().nullable(),
  organization_id: z.string().optional().nullable(),
});

export const ssoProviderMutatorSchema = z.object({
  id: ssoProviderIdSchema.optional(),
  provider_id: z.string().optional(),
  issuer: z.string().optional(),
  client_id: z.string().optional().nullable(),
  client_secret: z.string().optional().nullable(),
  discovery_endpoint: z.string().optional().nullable(),
  authorization_endpoint: z.string().optional().nullable(),
  token_endpoint: z.string().optional().nullable(),
  jwks_endpoint: z.string().optional().nullable(),
  userinfo_endpoint: z.string().optional().nullable(),
  scopes: z.string().optional().nullable(),
  additional_config: z.string().optional().nullable(),
  domain: z.string().optional(),
  created_at: z.date().optional(),
  updated_at: z.date().optional(),
  oidc_config: z.unknown().optional().nullable(),
  saml_config: z.string().optional().nullable(),
  user_id: z.string().optional().nullable(),
  organization_id: z.string().optional().nullable(),
});

export type SsoProvider = z.infer<typeof ssoProviderSchema>;
export type SsoProviderInitializer = z.infer<
  typeof ssoProviderInitializerSchema
>;
export type SsoProviderMutator = z.infer<typeof ssoProviderMutatorSchema>;
