// Generated by ts-to-zod
import { z } from "zod";

export const twoFactorIdSchema = z.string().and(
  z.object({
    __brand: z.literal("public.two_factor"),
  }),
);

const userIdSchema = z.any();

export const twoFactorSchema = z.object({
  id: twoFactorIdSchema,
  user_id: userIdSchema,
  secret: z.string().nullable(),
  backup_codes: z.string().nullable(),
  created_at: z.date(),
  updated_at: z.date(),
  verified: z.boolean(),
  failed_verification_count: z.number(),
  locked_until: z.date().nullable(),
});

export const twoFactorInitializerSchema = z.object({
  id: twoFactorIdSchema,
  user_id: userIdSchema,
  secret: z.string().optional().nullable(),
  backup_codes: z.string().optional().nullable(),
  created_at: z.date().optional(),
  updated_at: z.date().optional(),
  verified: z.boolean().optional(),
  failed_verification_count: z.number().optional(),
  locked_until: z.date().optional().nullable(),
});

export const twoFactorMutatorSchema = z.object({
  id: twoFactorIdSchema.optional(),
  user_id: userIdSchema.optional(),
  secret: z.string().optional().nullable(),
  backup_codes: z.string().optional().nullable(),
  created_at: z.date().optional(),
  updated_at: z.date().optional(),
  verified: z.boolean().optional(),
  failed_verification_count: z.number().optional(),
  locked_until: z.date().optional().nullable(),
});

export type TwoFactor = z.infer<typeof twoFactorSchema>;
export type TwoFactorInitializer = z.infer<typeof twoFactorInitializerSchema>;
export type TwoFactorMutator = z.infer<typeof twoFactorMutatorSchema>;
