// Generated by ts-to-zod
import { z } from "zod";

export const usersIdSchema = z.string().and(
  z.object({
    __brand: z.literal("auth.users"),
  }),
);

export const usersSchema = z.object({
  id: usersIdSchema,
  email: z.string().nullable(),
  password_hash: z.string(),
  raw_user_meta_data: z.unknown().nullable(),
  created_at: z.date().nullable(),
  updated_at: z.date().nullable(),
  role: z.string(),
  password_reset_token: z.string().nullable(),
  password_reset_expires: z.string().nullable(),
  is_active: z.boolean().nullable(),
  last_login_at: z.date().nullable(),
  mfa_secret: z.string().nullable(),
  mfa_totp_enabled: z.boolean().nullable(),
  mfa_email_enabled: z.boolean().nullable(),
  mfa_recovery_codes: z.unknown().nullable(),
  mfa_enforced: z.boolean().nullable(),
  magic_link_token: z.string().nullable(),
  magic_link_expires: z.date().nullable(),
  email_mfa_code: z.string().nullable(),
  email_mfa_expires_at: z.date().nullable(),
});

export const usersInitializerSchema = z.object({
  id: usersIdSchema,
  email: z.string().optional().nullable(),
  password_hash: z.string(),
  raw_user_meta_data: z.unknown().optional().nullable(),
  created_at: z.date().optional().nullable(),
  updated_at: z.date().optional().nullable(),
  role: z.string().optional(),
  password_reset_token: z.string().optional().nullable(),
  password_reset_expires: z.string().optional().nullable(),
  is_active: z.boolean().optional().nullable(),
  last_login_at: z.date().optional().nullable(),
  mfa_secret: z.string().optional().nullable(),
  mfa_totp_enabled: z.boolean().optional().nullable(),
  mfa_email_enabled: z.boolean().optional().nullable(),
  mfa_recovery_codes: z.unknown().optional().nullable(),
  mfa_enforced: z.boolean().optional().nullable(),
  magic_link_token: z.string().optional().nullable(),
  magic_link_expires: z.date().optional().nullable(),
  email_mfa_code: z.string().optional().nullable(),
  email_mfa_expires_at: z.date().optional().nullable(),
});

export const usersMutatorSchema = z.object({
  id: usersIdSchema.optional(),
  email: z.string().optional().nullable(),
  password_hash: z.string().optional(),
  raw_user_meta_data: z.unknown().optional().nullable(),
  created_at: z.date().optional().nullable(),
  updated_at: z.date().optional().nullable(),
  role: z.string().optional(),
  password_reset_token: z.string().optional().nullable(),
  password_reset_expires: z.string().optional().nullable(),
  is_active: z.boolean().optional().nullable(),
  last_login_at: z.date().optional().nullable(),
  mfa_secret: z.string().optional().nullable(),
  mfa_totp_enabled: z.boolean().optional().nullable(),
  mfa_email_enabled: z.boolean().optional().nullable(),
  mfa_recovery_codes: z.unknown().optional().nullable(),
  mfa_enforced: z.boolean().optional().nullable(),
  magic_link_token: z.string().optional().nullable(),
  magic_link_expires: z.date().optional().nullable(),
  email_mfa_code: z.string().optional().nullable(),
  email_mfa_expires_at: z.date().optional().nullable(),
});

export type Users = z.infer<typeof usersSchema>;
export type UsersInitializer = z.infer<typeof usersInitializerSchema>;
export type UsersMutator = z.infer<typeof usersMutatorSchema>;
