// Generated by ts-to-zod
import { z } from "zod";

export const userOidcLinksIdSchema = z.number().and(
  z.object({
    __brand: z.literal("public.user_oidc_links"),
  }),
);

const userIdSchema = z.any();

const oidcProvidersIdSchema = z.any();

export const userOidcLinksSchema = z.object({
  id: userOidcLinksIdSchema,
  user_id: userIdSchema,
  oidc_provider_id: oidcProvidersIdSchema,
  oidc_sub: z.string(),
  created_at: z.date().nullable(),
  updated_at: z.date().nullable(),
});

export const userOidcLinksInitializerSchema = z.object({
  id: userOidcLinksIdSchema.optional(),
  user_id: userIdSchema,
  oidc_provider_id: oidcProvidersIdSchema,
  oidc_sub: z.string(),
  created_at: z.date().optional().nullable(),
  updated_at: z.date().optional().nullable(),
});

export const userOidcLinksMutatorSchema = z.object({
  id: userOidcLinksIdSchema.optional(),
  user_id: userIdSchema.optional(),
  oidc_provider_id: oidcProvidersIdSchema.optional(),
  oidc_sub: z.string().optional(),
  created_at: z.date().optional().nullable(),
  updated_at: z.date().optional().nullable(),
});

export type UserOidcLinks = z.infer<typeof userOidcLinksSchema>;
export type UserOidcLinksInitializer = z.infer<
  typeof userOidcLinksInitializerSchema
>;
export type UserOidcLinksMutator = z.infer<typeof userOidcLinksMutatorSchema>;
