// Generated by ts-to-zod
import { z } from "zod";

export const userIgnoredUpdatesVariantIdSchema = z.string().and(
  z.object({
    __brand: z.literal("public.user_ignored_updates"),
  }),
);

const userIdSchema = z.any();

export const userIgnoredUpdatesSchema = z.object({
  user_id: userIdSchema,
  variant_id: userIgnoredUpdatesVariantIdSchema,
  ignored_at_timestamp: z.date(),
});

export const userIgnoredUpdatesInitializerSchema = z.object({
  user_id: userIdSchema,
  variant_id: userIgnoredUpdatesVariantIdSchema,
  ignored_at_timestamp: z.date(),
});

export const userIgnoredUpdatesMutatorSchema = z.object({
  user_id: userIdSchema.optional(),
  variant_id: userIgnoredUpdatesVariantIdSchema.optional(),
  ignored_at_timestamp: z.date().optional(),
});

export type UserIgnoredUpdates = z.infer<typeof userIgnoredUpdatesSchema>;
export type UserIgnoredUpdatesInitializer = z.infer<
  typeof userIgnoredUpdatesInitializerSchema
>;
export type UserIgnoredUpdatesMutator = z.infer<
  typeof userIgnoredUpdatesMutatorSchema
>;
