// Generated by ts-to-zod
import { z } from "zod";

export const userNutrientDisplayPreferencesIdSchema = z.number().and(
  z.object({
    __brand: z.literal("public.user_nutrient_display_preferences"),
  }),
);

const userIdSchema = z.any();

export const userNutrientDisplayPreferencesSchema = z.object({
  id: userNutrientDisplayPreferencesIdSchema,
  user_id: userIdSchema,
  view_group: z.string(),
  platform: z.string(),
  visible_nutrients: z.unknown(),
  created_at: z.date(),
  updated_at: z.date(),
});

export const userNutrientDisplayPreferencesInitializerSchema = z.object({
  id: userNutrientDisplayPreferencesIdSchema.optional(),
  user_id: userIdSchema,
  view_group: z.string(),
  platform: z.string(),
  visible_nutrients: z.unknown(),
  created_at: z.date().optional(),
  updated_at: z.date().optional(),
});

export const userNutrientDisplayPreferencesMutatorSchema = z.object({
  id: userNutrientDisplayPreferencesIdSchema.optional(),
  user_id: userIdSchema.optional(),
  view_group: z.string().optional(),
  platform: z.string().optional(),
  visible_nutrients: z.unknown().optional(),
  created_at: z.date().optional(),
  updated_at: z.date().optional(),
});

export type UserNutrientDisplayPreferences = z.infer<
  typeof userNutrientDisplayPreferencesSchema
>;
export type UserNutrientDisplayPreferencesInitializer = z.infer<
  typeof userNutrientDisplayPreferencesInitializerSchema
>;
export type UserNutrientDisplayPreferencesMutator = z.infer<
  typeof userNutrientDisplayPreferencesMutatorSchema
>;
