// Generated by ts-to-zod
import { z } from "zod";

export const userIdSchema = z.string().and(
  z.object({
    __brand: z.literal("public.user"),
  }),
);

export const userSchema = z.object({
  id: userIdSchema,
  email: z.string(),
  email_verified: z.boolean(),
  name: z.string().nullable(),
  created_at: z.date(),
  updated_at: z.date(),
  two_factor_enabled: z.boolean().nullable(),
  banned: z.boolean().nullable(),
  ban_reason: z.string().nullable(),
  ban_expires: z.date().nullable(),
  role: z.string().nullable(),
  mfa_email_enabled: z.boolean().nullable(),
  mfa_enforced: z.boolean().nullable(),
  email_mfa_code: z.string().nullable(),
  email_mfa_expires_at: z.date().nullable(),
  magic_link_token: z.string().nullable(),
  magic_link_expires: z.date().nullable(),
  mfa_totp_enabled: z.boolean().nullable(),
  image: z.string().nullable().optional(),
  last_login_at: z.date().nullable().optional(),
});

export const userInitializerSchema = z.object({
  id: userIdSchema.optional(),
  email: z.string(),
  email_verified: z.boolean().optional(),
  name: z.string().optional().nullable(),
  created_at: z.date().optional(),
  updated_at: z.date().optional(),
  two_factor_enabled: z.boolean().optional().nullable(),
  banned: z.boolean().optional().nullable(),
  ban_reason: z.string().optional().nullable(),
  ban_expires: z.date().optional().nullable(),
  role: z.string().optional().nullable(),
  mfa_email_enabled: z.boolean().optional().nullable(),
  mfa_enforced: z.boolean().optional().nullable(),
  email_mfa_code: z.string().optional().nullable(),
  email_mfa_expires_at: z.date().optional().nullable(),
  magic_link_token: z.string().optional().nullable(),
  magic_link_expires: z.date().optional().nullable(),
  mfa_totp_enabled: z.boolean().optional().nullable(),
  image: z.string().optional().nullable(),
  last_login_at: z.date().optional().nullable(),
});

export const userMutatorSchema = z.object({
  id: userIdSchema.optional(),
  email: z.string().optional(),
  email_verified: z.boolean().optional(),
  name: z.string().optional().nullable(),
  created_at: z.date().optional(),
  updated_at: z.date().optional(),
  two_factor_enabled: z.boolean().optional().nullable(),
  banned: z.boolean().optional().nullable(),
  ban_reason: z.string().optional().nullable(),
  ban_expires: z.date().optional().nullable(),
  role: z.string().optional().nullable(),
  mfa_email_enabled: z.boolean().optional().nullable(),
  mfa_enforced: z.boolean().optional().nullable(),
  email_mfa_code: z.string().optional().nullable(),
  email_mfa_expires_at: z.date().optional().nullable(),
  magic_link_token: z.string().optional().nullable(),
  magic_link_expires: z.date().optional().nullable(),
  mfa_totp_enabled: z.boolean().optional().nullable(),
  image: z.string().optional().nullable(),
  last_login_at: z.date().optional().nullable(),
});

export type User = z.infer<typeof userSchema>;
export type UserInitializer = z.infer<typeof userInitializerSchema>;
export type UserMutator = z.infer<typeof userMutatorSchema>;
