// Generated by ts-to-zod
import { z } from "zod";

export const verificationIdSchema = z.string().and(
  z.object({
    __brand: z.literal("public.verification"),
  }),
);

export const verificationSchema = z.object({
  id: verificationIdSchema,
  identifier: z.string(),
  value: z.string(),
  expires_at: z.date(),
  created_at: z.date().nullable(),
  updated_at: z.date().nullable(),
});

export const verificationInitializerSchema = z.object({
  id: verificationIdSchema.optional(),
  identifier: z.string(),
  value: z.string(),
  expires_at: z.date(),
  created_at: z.date().optional().nullable(),
  updated_at: z.date().optional().nullable(),
});

export const verificationMutatorSchema = z.object({
  id: verificationIdSchema.optional(),
  identifier: z.string().optional(),
  value: z.string().optional(),
  expires_at: z.date().optional(),
  created_at: z.date().optional().nullable(),
  updated_at: z.date().optional().nullable(),
});

export type Verification = z.infer<typeof verificationSchema>;
export type VerificationInitializer = z.infer<
  typeof verificationInitializerSchema
>;
export type VerificationMutator = z.infer<typeof verificationMutatorSchema>;
