// Generated by ts-to-zod
import { z } from "zod";

const userIdSchema = z.any();

export const vMctqAnalysisSchema = z.object({
  user_id: userIdSchema,
  date: z.date(),
  day_of_week: z.number(),
  day_type: z.string(),
  tst_hours: z.number(),
  mid_sleep: z.date(),
  bedtime: z.date(),
  wake_time: z.date(),
  wake_hour: z.number(),
});

export type VMctqAnalysis = z.infer<typeof vMctqAnalysisSchema>;
