// Generated by ts-to-zod
import { z } from "zod";

export const vMctqStatsSchema = z.object({
  user_id: z.string(),
  sd_workday: z.number(),
  sd_freeday: z.number(),
  sd_week: z.number(),
  sleep_need_ideal: z.number(),
  social_jetlag_hours: z.number(),
  workday_count: z.string(),
  freeday_count: z.string(),
  confidence: z.string(),
});

export type VMctqStats = z.infer<typeof vMctqStatsSchema>;
