// Generated by ts-to-zod
import { z } from "zod";

const userIdSchema = z.any();

export const waterIntakeSchema = z.object({
  id: z.string(),
  user_id: z.string(),
  entry_date: z.date(),
  created_at: z.date(),
  updated_at: z.date(),
  water_ml: z.number().nullable(),
  created_by_user_id: userIdSchema.nullable(),
  updated_by_user_id: userIdSchema.nullable(),
  source: z.string().max(50).nullable().optional(),
});

export const waterIntakeInitializerSchema = z.object({
  id: z.string().optional(),
  user_id: z.string(),
  entry_date: z.date().optional(),
  created_at: z.date().optional(),
  updated_at: z.date().optional(),
  water_ml: z.number().optional().nullable(),
  created_by_user_id: userIdSchema.optional().nullable(),
  updated_by_user_id: userIdSchema.optional().nullable(),
  source: z.string().max(50).optional().nullable(),
});

export const waterIntakeMutatorSchema = z.object({
  id: z.string().optional(),
  user_id: z.string().optional(),
  entry_date: z.date().optional(),
  created_at: z.date().optional(),
  updated_at: z.date().optional(),
  water_ml: z.number().optional().nullable(),
  created_by_user_id: userIdSchema.optional().nullable(),
  updated_by_user_id: userIdSchema.optional().nullable(),
  source: z.string().max(50).optional().nullable(),
});

export type WaterIntake = z.infer<typeof waterIntakeSchema>;
export type WaterIntakeInitializer = z.infer<
  typeof waterIntakeInitializerSchema
>;
export type WaterIntakeMutator = z.infer<typeof waterIntakeMutatorSchema>;
