// Generated by ts-to-zod
import { z } from "zod";

export const weeklyGoalPlansIdSchema = z.string().and(
  z.object({
    __brand: z.literal("public.weekly_goal_plans"),
  }),
);

const userIdSchema = z.any();

const goalPresetsIdSchema = z.any();

export const weeklyGoalPlansSchema = z.object({
  id: weeklyGoalPlansIdSchema,
  user_id: userIdSchema,
  plan_name: z.string(),
  start_date: z.date(),
  end_date: z.date().nullable(),
  is_active: z.boolean(),
  monday_preset_id: goalPresetsIdSchema.nullable(),
  tuesday_preset_id: goalPresetsIdSchema.nullable(),
  wednesday_preset_id: goalPresetsIdSchema.nullable(),
  thursday_preset_id: goalPresetsIdSchema.nullable(),
  friday_preset_id: goalPresetsIdSchema.nullable(),
  saturday_preset_id: goalPresetsIdSchema.nullable(),
  sunday_preset_id: goalPresetsIdSchema.nullable(),
  created_at: z.date(),
  updated_at: z.date(),
});

export const weeklyGoalPlansInitializerSchema = z.object({
  id: weeklyGoalPlansIdSchema.optional(),
  user_id: userIdSchema,
  plan_name: z.string(),
  start_date: z.date(),
  end_date: z.date().optional().nullable(),
  is_active: z.boolean().optional(),
  monday_preset_id: goalPresetsIdSchema.optional().nullable(),
  tuesday_preset_id: goalPresetsIdSchema.optional().nullable(),
  wednesday_preset_id: goalPresetsIdSchema.optional().nullable(),
  thursday_preset_id: goalPresetsIdSchema.optional().nullable(),
  friday_preset_id: goalPresetsIdSchema.optional().nullable(),
  saturday_preset_id: goalPresetsIdSchema.optional().nullable(),
  sunday_preset_id: goalPresetsIdSchema.optional().nullable(),
  created_at: z.date().optional(),
  updated_at: z.date().optional(),
});

export const weeklyGoalPlansMutatorSchema = z.object({
  id: weeklyGoalPlansIdSchema.optional(),
  user_id: userIdSchema.optional(),
  plan_name: z.string().optional(),
  start_date: z.date().optional(),
  end_date: z.date().optional().nullable(),
  is_active: z.boolean().optional(),
  monday_preset_id: goalPresetsIdSchema.optional().nullable(),
  tuesday_preset_id: goalPresetsIdSchema.optional().nullable(),
  wednesday_preset_id: goalPresetsIdSchema.optional().nullable(),
  thursday_preset_id: goalPresetsIdSchema.optional().nullable(),
  friday_preset_id: goalPresetsIdSchema.optional().nullable(),
  saturday_preset_id: goalPresetsIdSchema.optional().nullable(),
  sunday_preset_id: goalPresetsIdSchema.optional().nullable(),
  created_at: z.date().optional(),
  updated_at: z.date().optional(),
});

export type WeeklyGoalPlans = z.infer<typeof weeklyGoalPlansSchema>;
export type WeeklyGoalPlansInitializer = z.infer<
  typeof weeklyGoalPlansInitializerSchema
>;
export type WeeklyGoalPlansMutator = z.infer<
  typeof weeklyGoalPlansMutatorSchema
>;
