// Generated by ts-to-zod
import { z } from "zod";

export const workoutPlanTemplateAssignmentsIdSchema = z.number().and(
  z.object({
    __brand: z.literal("public.workout_plan_template_assignments"),
  }),
);

const workoutPlanTemplatesIdSchema = z.any();

const workoutPresetsIdSchema = z.any();

const exercisesIdSchema = z.any();

export const workoutPlanTemplateAssignmentsSchema = z.object({
  id: workoutPlanTemplateAssignmentsIdSchema,
  template_id: workoutPlanTemplatesIdSchema,
  day_of_week: z.number(),
  workout_preset_id: workoutPresetsIdSchema.nullable(),
  exercise_id: exercisesIdSchema.nullable(),
  created_at: z.date().nullable(),
  updated_at: z.date().nullable(),
  sort_order: z.number().nullable(),
});

export const workoutPlanTemplateAssignmentsInitializerSchema = z.object({
  id: workoutPlanTemplateAssignmentsIdSchema.optional(),
  template_id: workoutPlanTemplatesIdSchema,
  day_of_week: z.number(),
  workout_preset_id: workoutPresetsIdSchema.optional().nullable(),
  exercise_id: exercisesIdSchema.optional().nullable(),
  created_at: z.date().optional().nullable(),
  updated_at: z.date().optional().nullable(),
  sort_order: z.number().optional().nullable(),
});

export const workoutPlanTemplateAssignmentsMutatorSchema = z.object({
  id: workoutPlanTemplateAssignmentsIdSchema.optional(),
  template_id: workoutPlanTemplatesIdSchema.optional(),
  day_of_week: z.number().optional(),
  workout_preset_id: workoutPresetsIdSchema.optional().nullable(),
  exercise_id: exercisesIdSchema.optional().nullable(),
  created_at: z.date().optional().nullable(),
  updated_at: z.date().optional().nullable(),
  sort_order: z.number().optional().nullable(),
});

export type WorkoutPlanTemplateAssignments = z.infer<
  typeof workoutPlanTemplateAssignmentsSchema
>;
export type WorkoutPlanTemplateAssignmentsInitializer = z.infer<
  typeof workoutPlanTemplateAssignmentsInitializerSchema
>;
export type WorkoutPlanTemplateAssignmentsMutator = z.infer<
  typeof workoutPlanTemplateAssignmentsMutatorSchema
>;
