import crypto from 'crypto';
import { log } from '../config/logging.js';
const ENCRYPTION_KEY_RAW = process.env.SPARKY_FITNESS_API_ENCRYPTION_KEY;
if (!ENCRYPTION_KEY_RAW) {
  log(
    'error',
    'Encryption key (SPARKY_FITNESS_API_ENCRYPTION_KEY) is missing. Update your environment variable and try again.'
  );
  throw new Error('SPARKY_FITNESS_API_ENCRYPTION_KEY is missing.');
}
// The key generated by `openssl rand -base64 32` is 44 characters long.
// The key generated by `node -e "console.log(require('crypto').randomBytes(32).toString('hex'))"` is 64 characters long.
if (ENCRYPTION_KEY_RAW.length !== 64 && ENCRYPTION_KEY_RAW.length !== 44) {
  log(
    'error',
    `Encryption key (SPARKY_FITNESS_API_ENCRYPTION_KEY) has an invalid length (${ENCRYPTION_KEY_RAW.length}). Expected 64 hex characters or 44 Base64 characters.`
  );
  throw new Error('SPARKY_FITNESS_API_ENCRYPTION_KEY has invalid length.');
}
const ENCRYPTION_KEY =
  ENCRYPTION_KEY_RAW.length === 44
    ? Buffer.from(ENCRYPTION_KEY_RAW, 'base64').toString('hex')
    : ENCRYPTION_KEY_RAW;
// Utility functions for encryption and decryption
// eslint-disable-next-line @typescript-eslint/no-explicit-any
async function encrypt(text: any, key: any) {
  log('debug', `Encrypting text with key of length: ${key.length}`);
  if (!text) {
    return { encryptedText: null, iv: null, tag: null };
  }
  const iv = crypto.randomBytes(12); // GCM recommended IV size is 12 bytes
  const cipher = crypto.createCipheriv(
    'aes-256-gcm',
    Buffer.from(key, 'hex'),
    iv
  );
  let encrypted = cipher.update(text, 'utf8', 'base64');
  encrypted += cipher.final('base64');
  const tag = cipher.getAuthTag().toString('base64');
  return { encryptedText: encrypted, iv: iv.toString('base64'), tag: tag };
}

async function decrypt(
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  encryptedText: any,
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  ivString: any,
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  tagString: any,
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  key: any
) {
  log('debug', `Decrypting text with key of length: ${key.length}`);
  if (!encryptedText || !ivString || !tagString) {
    log(
      'warn',
      'Attempted to decrypt null or incomplete data. Returning null.'
    );
    return null;
  }
  const iv = Buffer.from(ivString, 'base64');
  const tag = Buffer.from(tagString, 'base64');
  const decipher = crypto.createDecipheriv(
    'aes-256-gcm',
    Buffer.from(key, 'hex'),
    iv
  );
  decipher.setAuthTag(tag);
  let decrypted = decipher.update(encryptedText, 'base64', 'utf8');
  decrypted += decipher.final('utf8');
  return decrypted;
}
export { encrypt };
export { decrypt };
export { ENCRYPTION_KEY };
export default {
  encrypt,
  decrypt,
  ENCRYPTION_KEY,
};
