import React, { useCallback, useMemo, useState } from 'react';
import {
  Alert,
  FlatList,
  Pressable,
  RefreshControl,
  Text,
  View,
} from 'react-native';
import { useTranslation } from 'react-i18next';
import { useSafeAreaInsets } from 'react-native-safe-area-context';
import Toast from 'react-native-toast-message';
import { useCSSVariable } from 'uniwind';
import FooterActionBar from '../components/FooterActionBar';
import Icon from '../components/Icon';
import StatusView from '../components/StatusView';
import Button from '../components/ui/Button';
import {
  useDeleteMealPlan,
  useDuplicateMealPlan,
  useMealPlans,
  useServerConnection,
} from '../hooks';
import { useScreenHeader } from '../hooks/useScreenHeader';
import { useNativeIOSHeadersActive } from '../services/nativeTabBarPreference';
import type { MealPlanAssignment, MealPlanTemplate } from '../types/mealPlans';
import type { RootStackScreenProps } from '../types/navigation';
import { formatDateLabel, toLocalDateString } from '../utils/dateUtils';

type MealPlansScreenProps = RootStackScreenProps<'MealPlans'>;

function assignmentLabel(
  assignment: MealPlanAssignment,
  weekdays: readonly string[]
): string {
  const weekday = weekdays[assignment.day_of_week] ?? '';
  const mealType = assignment.meal_type || assignment.meal_type_id;
  const itemName =
    assignment.item_type === 'meal'
      ? assignment.meal_name || assignment.meal_id
      : assignment.food_name || assignment.food_id;
  const quantity = assignment.quantity ?? 1;
  const unit = assignment.unit || 'serving';
  return [weekday, mealType, itemName, `${quantity} ${unit}`]
    .filter(Boolean)
    .join(' · ');
}

const MealPlansScreen: React.FC<MealPlansScreenProps> = ({ navigation }) => {
  const { t, i18n } = useTranslation();
  const insets = useSafeAreaInsets();
  const usesNativeHeader = useNativeIOSHeadersActive();
  const [accentColor] = useCSSVariable(['--color-accent-primary']) as [string];
  const [refreshing, setRefreshing] = useState(false);
  const { isConnected, isLoading: isConnectionLoading } = useServerConnection();
  const { mealPlans, isLoading, isError, refetch } = useMealPlans({
    enabled: isConnected,
  });
  const { duplicateMealPlanAsync, isPending: isDuplicating } =
    useDuplicateMealPlan();
  const { deleteMealPlanAsync, isPending: isDeleting } = useDeleteMealPlan();
  const dateLocale = i18n.language.startsWith('pl') ? 'pl-PL' : 'en-US';
  const weekdays = useMemo(
    () => [
      t('mealPlans.weekdaysShort.sunday', { defaultValue: 'Sun' }),
      t('mealPlans.weekdaysShort.monday', { defaultValue: 'Mon' }),
      t('mealPlans.weekdaysShort.tuesday', { defaultValue: 'Tue' }),
      t('mealPlans.weekdaysShort.wednesday', { defaultValue: 'Wed' }),
      t('mealPlans.weekdaysShort.thursday', { defaultValue: 'Thu' }),
      t('mealPlans.weekdaysShort.friday', { defaultValue: 'Fri' }),
      t('mealPlans.weekdaysShort.saturday', { defaultValue: 'Sat' }),
    ],
    [t]
  );

  const showError = useCallback(
    (title: string) => {
      Toast.show({
        type: 'error',
        text1: title,
        text2: t('common.tryAgain', { defaultValue: 'Please try again.' }),
      });
    },
    [t]
  );

  const duplicate = useCallback(
    async (plan: MealPlanTemplate) => {
      try {
        await duplicateMealPlanAsync(plan.id, toLocalDateString(new Date()));
        Toast.show({
          type: 'success',
          text1: t('mealPlans.duplicateSuccess', {
            defaultValue: 'Meal plan duplicated',
          }),
          text2: t('mealPlans.duplicateInactive', {
            defaultValue: 'The copy is inactive so you can review it first.',
          }),
        });
      } catch {
        showError(
          t('mealPlans.duplicateFailed', {
            defaultValue: 'Failed to duplicate meal plan',
          })
        );
      }
    },
    [duplicateMealPlanAsync, showError, t]
  );

  const confirmDelete = useCallback(
    (plan: MealPlanTemplate) => {
      Alert.alert(
        t('mealPlans.deleteTitle', { defaultValue: 'Delete meal plan' }),
        t('mealPlans.deleteMessage', {
          defaultValue:
            'Delete {{name}}? Future diary entries generated by this plan will be removed.',
          name: plan.plan_name,
        }),
        [
          {
            text: t('common.cancel', { defaultValue: 'Cancel' }),
            style: 'cancel',
          },
          {
            text: t('common.delete', { defaultValue: 'Delete' }),
            style: 'destructive',
            onPress: async () => {
              try {
                await deleteMealPlanAsync(
                  plan.id,
                  toLocalDateString(new Date())
                );
                Toast.show({
                  type: 'success',
                  text1: t('mealPlans.deleteSuccess', {
                    defaultValue: 'Meal plan deleted',
                  }),
                });
              } catch {
                showError(
                  t('mealPlans.deleteFailed', {
                    defaultValue: 'Failed to delete meal plan',
                  })
                );
              }
            },
          },
        ]
      );
    },
    [deleteMealPlanAsync, showError, t]
  );

  const onRefresh = useCallback(async () => {
    setRefreshing(true);
    await refetch();
    setRefreshing(false);
  }, [refetch]);

  const header = useScreenHeader({
    title: t('mealPlans.title', { defaultValue: 'Meal plans' }),
    left: { kind: 'back' },
    right: {
      kind: 'icon',
      sfSymbol: 'plus',
      ionicon: 'add',
      accessibilityLabel: t('mealPlans.create', {
        defaultValue: 'Create meal plan',
      }),
      onPress: () => navigation.navigate('MealPlanForm'),
    },
  });

  const renderPlan = ({ item }: { item: MealPlanTemplate }) => (
    <View className="bg-surface rounded-xl px-4 py-4 mb-3 shadow-sm">
      <Pressable
        accessibilityRole="button"
        onPress={() => navigation.navigate('MealPlanForm', { template: item })}
        style={({ pressed }) => (pressed ? { opacity: 0.7 } : null)}
      >
        <View className="flex-row items-start justify-between">
          <View className="flex-1 mr-3">
            <Text className="text-lg font-semibold text-text-primary">
              {item.plan_name}
            </Text>
            {item.description ? (
              <Text className="text-sm text-text-secondary mt-1">
                {item.description}
              </Text>
            ) : null}
          </View>
          <View
            className={
              item.is_active
                ? 'bg-success-soft px-2.5 py-1 rounded-full'
                : 'bg-raised px-2.5 py-1 rounded-full'
            }
          >
            <Text
              className={
                item.is_active
                  ? 'text-success text-xs font-semibold'
                  : 'text-text-secondary text-xs font-semibold'
              }
            >
              {item.is_active
                ? t('mealPlans.active', { defaultValue: 'Active' })
                : t('mealPlans.inactive', { defaultValue: 'Inactive' })}
            </Text>
          </View>
        </View>
        <Text className="text-sm text-text-secondary mt-3">
          {item.end_date
            ? t('mealPlans.dateRange', {
                defaultValue: '{{start}} – {{end}}',
                start: formatDateLabel(
                  item.start_date.slice(0, 10),
                  t,
                  dateLocale
                ),
                end: formatDateLabel(item.end_date.slice(0, 10), t, dateLocale),
              })
            : t('mealPlans.starting', {
                defaultValue: 'Starting {{date}}',
                date: formatDateLabel(
                  item.start_date.slice(0, 10),
                  t,
                  dateLocale
                ),
              })}
        </Text>
        <View className="mt-3">
          {item.assignments.slice(0, 3).map((assignment, index) => (
            <Text
              key={assignment.id ?? `${assignment.item_type}-${index}`}
              className="text-sm text-text-primary mb-1"
            >
              {assignmentLabel(assignment, weekdays)}
            </Text>
          ))}
          {item.assignments.length > 3 ? (
            <Text className="text-sm text-text-secondary">
              {t('mealPlans.moreAssignments', {
                defaultValue: '+{{count}} more',
                defaultValue_one: '+{{count}} more',
                defaultValue_other: '+{{count}} more',
                count: item.assignments.length - 3,
              })}
            </Text>
          ) : null}
        </View>
      </Pressable>
      <View className="flex-row justify-end mt-2 border-t border-border-subtle pt-2">
        <Pressable
          accessibilityRole="button"
          accessibilityLabel={t('mealPlans.duplicateNamed', {
            defaultValue: 'Duplicate {{name}}',
            name: item.plan_name,
          })}
          disabled={isDuplicating || isDeleting}
          className="p-3"
          onPress={() => void duplicate(item)}
        >
          <Icon name="copy" size={20} color={accentColor} />
        </Pressable>
        <Pressable
          accessibilityRole="button"
          accessibilityLabel={t('mealPlans.deleteNamed', {
            defaultValue: 'Delete {{name}}',
            name: item.plan_name,
          })}
          disabled={isDuplicating || isDeleting}
          className="p-3"
          onPress={() => confirmDelete(item)}
        >
          <Icon name="trash" size={20} color="#dc2626" />
        </Pressable>
      </View>
    </View>
  );

  const content = () => {
    if (!isConnectionLoading && !isConnected) {
      return (
        <StatusView
          icon="cloud-offline"
          iconTone="muted"
          title={t('mealPlans.noServer', {
            defaultValue: 'No server configured',
          })}
          subtitle={t('mealPlans.noServerSubtitle', {
            defaultValue:
              'Configure your server connection to manage meal plans.',
          })}
          action={{
            label: t('mealPlans.goToSettings', {
              defaultValue: 'Go to Settings',
            }),
            onPress: () => navigation.navigate('Tabs', { screen: 'Settings' }),
            variant: 'primary',
          }}
        />
      );
    }
    if (isLoading || isConnectionLoading) {
      return (
        <StatusView
          loading
          title={t('mealPlans.loading', {
            defaultValue: 'Loading meal plans...',
          })}
        />
      );
    }
    if (isError) {
      return (
        <StatusView
          icon="alert-circle"
          iconTone="danger"
          title={t('mealPlans.loadFailed', {
            defaultValue: 'Failed to load meal plans',
          })}
          subtitle={t('mealPlans.loadFailedSubtitle', {
            defaultValue: 'Check your connection and try again.',
          })}
          action={{
            label: t('common.retry', { defaultValue: 'Retry' }),
            onPress: () => void refetch(),
            variant: 'primary',
          }}
        />
      );
    }
    return (
      <FlatList
        data={mealPlans}
        keyExtractor={(item) => item.id}
        renderItem={renderPlan}
        contentContainerStyle={{
          paddingHorizontal: 16,
          paddingTop: 16,
          paddingBottom: insets.bottom + 16,
          flexGrow: 1,
        }}
        refreshControl={
          <RefreshControl
            refreshing={refreshing}
            onRefresh={onRefresh}
            tintColor={accentColor}
          />
        }
        ListHeaderComponent={
          mealPlans.length > 0 ? (
            <View className="bg-raised rounded-xl px-4 py-3 mb-4">
              <Text className="text-sm text-text-secondary">
                {t('mealPlans.futureNotice', {
                  defaultValue:
                    'Active plans add entries to future diary days. Editing or deleting a plan updates future generated entries.',
                })}
              </Text>
            </View>
          ) : null
        }
        ListEmptyComponent={
          <StatusView
            inline
            icon="meal"
            title={t('mealPlans.emptyTitle', {
              defaultValue: 'No meal plans yet',
            })}
            subtitle={t('mealPlans.emptySubtitle', {
              defaultValue:
                'Schedule reusable meals on selected weekdays for easier meal prep.',
            })}
            action={{
              label: t('mealPlans.create', {
                defaultValue: 'Create meal plan',
              }),
              onPress: () => navigation.navigate('MealPlanForm'),
              variant: 'primary',
            }}
          />
        }
      />
    );
  };

  return (
    <View
      className="flex-1 bg-background"
      style={usesNativeHeader ? undefined : { paddingTop: insets.top }}
    >
      {header}
      {content()}
      {mealPlans.length > 0 && !isLoading && !isError ? (
        <FooterActionBar>
          <Button onPress={() => navigation.navigate('MealPlanForm')}>
            {t('mealPlans.create', { defaultValue: 'Create meal plan' })}
          </Button>
        </FooterActionBar>
      ) : null}
    </View>
  );
};

export default MealPlansScreen;
