import { z } from "zod";

export const foodPhotoEstimateConfidenceSchema = z.enum([
  "high",
  "medium",
  "low",
]);

/**
 * The micronutrients the estimate carries alongside the core macros.
 *
 * Every one is optional — never `.default()`, which would make the PARSED type
 * required and force every existing fixture and item literal to list all
 * eleven. A model that ignores them, or an estimate produced before they
 * existed, still parses, and `asPortionMacros` coerces a missing value to 0 on
 * the way into the maths. They scale with
 * the row's weight exactly like the macros do — see `ESTIMATE_ALL_MACRO_KEYS`
 * in `foodPhotoEstimateMath.ts`, which is what the scaling maths iterates.
 *
 * Units follow the `food_variants` columns they end up in, not the estimate's
 * gram-centric macro names: mg for minerals, mcg for vitamin A.
 */
export const foodPhotoEstimateMicrosShape = {
  saturated_fat_g: z.number().optional(),
  polyunsaturated_fat_g: z.number().optional(),
  monounsaturated_fat_g: z.number().optional(),
  trans_fat_g: z.number().optional(),
  cholesterol_mg: z.number().optional(),
  sodium_mg: z.number().optional(),
  potassium_mg: z.number().optional(),
  calcium_mg: z.number().optional(),
  iron_mg: z.number().optional(),
  vitamin_a_mcg: z.number().optional(),
  vitamin_c_mg: z.number().optional(),
};

/**
 * The nutrition every layer of this flow speaks in. Extracted so the item,
 * totals, and match schemas cannot drift apart.
 *
 * These numbers are always on the PORTION basis (they describe the estimated
 * grams of that row), never per-100 g. See `foodPhotoEstimateMath.ts` — the
 * branded `PortionMacros` / `Per100gMacros` types enforce that distinction in
 * code; this schema is just the wire shape.
 */
export const foodPhotoEstimateMacrosSchema = z.object({
  calories_kcal: z.number(),
  protein_g: z.number(),
  carbs_g: z.number(),
  fat_g: z.number(),
  fiber_g: z.number(),
  sugar_g: z.number(),
  ...foodPhotoEstimateMicrosShape,
});

/**
 * A food from the user's own database that the server believes corresponds to
 * a detected ingredient.
 *
 * The server ATTACHES this; it never rewrites the item's own macros with it.
 * Substituting silently would (a) change the numbers an already-shipped mobile
 * build is displaying, and (b) assume "Chicken Thigh" in the library is the
 * same chicken thigh that is in this photo. The client shows the match as an
 * explicit, reversible choice instead.
 */
export const foodPhotoEstimateMatchSchema = z.object({
  /**
   * Present for a food already in the user's database. ABSENT for a match that
   * came from an external provider (OpenFoodFacts, USDA, …) — that food does
   * not exist locally yet, so applying it creates one from the provider's
   * nutrition instead of reusing a row.
   */
  food_id: z.string().uuid().optional(),
  variant_id: z.string().uuid().optional(),
  /** Provenance for a provider match, carried onto the food that gets created. */
  provider_type: z.string().optional(),
  provider_external_id: z.string().optional(),

  food_name: z.string(),
  brand: z.string().nullable(),
  serving_size: z.number(),
  serving_unit: z.string(),
  /** 0..1, from `scoreFoodMatch`. Below MATCH_MIN_SCORE is never attached. */
  match_score: z.number().min(0).max(1),
  match_source: z.enum([
    "exact_name",
    "token_overlap",
    "recent_usage",
    /**
     * From the external provider cascade. `prompts/chatbot-full-food.md` makes
     * verified provider data preferred over an AI guess; this carries the same
     * rule into the photo flow.
     */
    "provider",
  ]),
  is_own_food: z.boolean(),
  /** False when the matched variant is measured in cups/slices/etc. */
  gram_convertible: z.boolean(),
  /**
   * The matched food's real nutrition, already scaled to this item's
   * `estimated_grams`. Null when `gram_convertible` is false, so the client
   * hides the swap affordance rather than inventing a number.
   */
  scaled: foodPhotoEstimateMacrosSchema.nullable(),
});

/**
 * One detected ingredient.
 *
 * Every field added after the original release is `.optional()` and the object
 * stays `.passthrough()`, so a shipped App Store build that predates them
 * simply ignores them. Never make one of these required, and never change what
 * an existing field means — an old client cannot be updated in lockstep.
 */
export const foodPhotoEstimateItemSchema = z
  .object({
    name: z.string(),
    estimated_grams: z.number(),
    portion_description: z.string(),
    preparation: z.string(),
    calories_kcal: z.number(),
    protein_g: z.number(),
    carbs_g: z.number(),
    fat_g: z.number(),
    fiber_g: z.number(),
    sugar_g: z.number(),
    ...foodPhotoEstimateMicrosShape,
    item_confidence: foodPhotoEstimateConfidenceSchema,
    assumptions: z.array(z.string()).default([]),

    /**
     * Stable identity for a row, assigned BY THE SERVER (`crypto.randomUUID()`)
     * after the model responds — never generated by the model, which would let
     * a hallucinated duplicate id collapse two rows in a React list. Clients
     * that predate this field fall back to the array index.
     */
    item_id: z.string().optional(),

    /**
     * Generic searchable name with preparation/brand/quantity words stripped
     * ("chicken thigh" for "grilled chicken thigh"). Used as the food-database
     * query. Required in the provider JSON schema (models comply better with
     * required fields) but optional here, so a provider that omits it degrades
     * to `name` instead of failing the whole response with PARSE_ERROR.
     */
    canonical_name: z.string().optional(),

    /** Best database match, or null when nothing scored above the threshold. */
    match: foodPhotoEstimateMatchSchema.nullable().optional(),

    /** Runner-up matches for "use a different food". Capped to bound payload size. */
    alternates: z.array(foodPhotoEstimateMatchSchema).max(2).optional(),

    /**
     * UI hint only: true when the match is strong enough to apply on open.
     * The server still does not rewrite the macros — the client applies it.
     */
    preselect_match: z.boolean().optional(),
  })
  .passthrough();

export const foodPhotoEstimateTotalsSchema = foodPhotoEstimateMacrosSchema
  .extend({
    total_grams: z.number(),
  })
  .passthrough();

export const foodPhotoEstimateResponseSchema = z
  .object({
    meal_summary: z.string(),
    overall_confidence: foodPhotoEstimateConfidenceSchema,
    confidence_reason: z.string(),
    items: z.array(foodPhotoEstimateItemSchema),
    totals: foodPhotoEstimateTotalsSchema,
    user_weight_reconciliation: z.string(),
    clarifying_questions: z.array(z.string()).default([]),

    /** Added after the original release — optional, see the item schema note. */
    match_summary: z
      .object({
        item_count: z.number().int().nonnegative(),
        matched_count: z.number().int().nonnegative(),
        own_food_count: z.number().int().nonnegative(),
      })
      .optional(),
  })
  .passthrough();

export const foodPhotoEstimateErrorCodeSchema = z.enum([
  "INVALID_REQUEST",
  "IMAGE_TOO_LARGE",
  "UNSUPPORTED_MIME_TYPE",
  "NO_AI_CONFIGURED",
  "UNSUPPORTED_PROVIDER",
  "API_KEY_MISSING",
  "CONTENT_BLOCKED",
  "PARSE_ERROR",
  "UPSTREAM_ERROR",
  "PRIVATE_NETWORK_FORBIDDEN",
  "TIMEOUT",
]);

export const foodPhotoEstimateErrorResponseSchema = z.object({
  error: z.string(),
  code: foodPhotoEstimateErrorCodeSchema,
});

export type FoodPhotoEstimateConfidence = z.infer<
  typeof foodPhotoEstimateConfidenceSchema
>;
export type FoodPhotoEstimateMacros = z.infer<
  typeof foodPhotoEstimateMacrosSchema
>;
export type FoodPhotoEstimateMatch = z.infer<
  typeof foodPhotoEstimateMatchSchema
>;
export type FoodPhotoEstimateMatchSource =
  FoodPhotoEstimateMatch["match_source"];
export type FoodPhotoEstimateItem = z.infer<typeof foodPhotoEstimateItemSchema>;
export type FoodPhotoEstimateTotals = z.infer<
  typeof foodPhotoEstimateTotalsSchema
>;
export type FoodPhotoEstimateResponse = z.infer<
  typeof foodPhotoEstimateResponseSchema
>;
export type FoodPhotoEstimateErrorCode = z.infer<
  typeof foodPhotoEstimateErrorCodeSchema
>;
export type FoodPhotoEstimateErrorResponse = z.infer<
  typeof foodPhotoEstimateErrorResponseSchema
>;
